### ISSUE TITLE
Service loadbalancer does not expose services in kube-system namespace

### ISSUE THREAD

**Issue by asim** [kubernetes/contrib#103]
The documentation for the service loadbalancer indicates that the kube-ui can be reached via the default configuration however the loadbalancer does not query the kube-system namespace so nothing is actually exposed. Please either change the documentation to reflect this or allow a way to query multiple namespaces e.g kube-system, default, etc.

**Comment by bprashanth** [comment]
@asim thanks

@preillyme the ui interacts weirdly when receiving traffic through service.Type=LoadBalancer. I can curl and things work just fine, but something like:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-ui
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeUI
  name: kube-ui2
  namespace: kube-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: kube-ui
  sessionAffinity: None
  type: LoadBalancer
```

Which should just forward packets via gce's L4 cloud loadbalancer, only gives me the blue header. What am I missing? does the master proxy add some headers? maybe destination ip is the problem?
