### ISSUE TITLE
Can't POST Ingress to API using curl, but kubectl works fine.

### ISSUE THREAD

**Issue by brandong954** [kubernetes/contrib#1150]
Trying to execute: 

`curl -X POST -d @ingress.yaml  -H 'Content-type:application/yaml' http://127.0.0.1:8080/apis/extensions/v1beta1/namespaces/somenamespace/ingresses`

ingress.yaml:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echomap
  namespace: somenamespace
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: echoheaders-x
          servicePort: 80
  - host: bar.baz.com
    http:
      paths:
      - path: /bar
        backend:
          serviceName: echoheaders-y
          servicePort: 80
      - path: /foo
        backend:
          serviceName: echoheaders-x
          servicePort: 80
```

But the call fails with:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the object provided is unrecognized (must be of type Ingress): yaml: mapping values are not allowed in this context",
  "reason": "BadRequest",
  "code": 400
}
```

Even though when executing `kubectl create -f ./ingress.yaml`, everything works just fine.
