### ISSUE TITLE
[nginx-ingress-controller] JWT and Client SSL Verify

### ISSUE THREAD

**Issue by dnascimento** [kubernetes/contrib#1327]
NGINX can handle JWT token validation to provide authentication on APIs. 
Verify Client SSL Certificate should also be possible.

It requires to change the spec in kubernetes project to add:

```
 jwt:
    - hosts:
        - XXXXXX
 client-verify:
     - hosts:
         - XXXXX
```
