### ISSUE TITLE
Nginx Ingress Controller - global default certificate

### ISSUE THREAD

**Issue by yvespp** [kubernetes/contrib#1331]
I want to be able to configure a certificate in the namespace of the Ingress Controller and it should be used for all Ingress rules, regardless of their namespace and their Ingress TLS configuration.
An Individual Ingress resource should still be able to overwrite it.

**Use-case:**
Wild card DNS and certificate are set up for *.mycorp.com. A user can now setup an ingress rule for myns.mycorp.com/app1 and it will be protected with TLS without having to configure certs or a TLS ingress rule.

**Implementation proposal:**
New optional command line parameter for the controller: a reference to the default secret.
If present and the cert matches spec.rules.host, TLS will be enabled.
If a rule specifies it's own cert, it will overwrite the default cert.
TCP and UDP services are not affected.

What do you think? Would it make sense to add this to the controller?

I tried to solve this via this Ingress resource that the doc mentions but I could not get it to work:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: no-rules-map
spec:
  tls:
    secretName: testsecret
  backend:
    serviceName: s1
    servicePort: 80
```
How is this supposed to work?
Also all 30 seconds or so the following log message appears in the Ingress controller log:
```
I0708 14:26:54.489232       1 controller.go:933] Using the secret ingresssecret as source for the default SSL certificate
```
