### ISSUE TITLE
Creating tokens for new nodes

### ISSUE THREAD

**Issue by aabed** [kubernetes/contrib#1371]
Everything works fine when you create a full cluster, but when you want to add a new node to the cluster with _--limit_ option the task for generating tokens is never called because

```
- include: gen_tokens.yml
  when: inventory_hostname == groups['masters'][0] 
```

So how about adding a condition so that it would generate token for the new added node

```
- name: Check existence for token files
  stat: "{{ kube_script_dir }}/kube-gen-token.sh {{ item[0] }}-{{ item[1] }}"
  with_nested:
    - [ "system:controller_manager", "system:scheduler", "system:kubectl" ]
    - "{{ groups['masters'] }}"
  register: token_file 
```

```
- include: gen_tokens.yml
  when: (inventory_hostname == groups['masters'][0]) or (token_file.isreg == False ) 
```

**Comment by aabed** [comment]
@eparis

**Comment by ingvagabund** [comment]
Hey @aabed, what about to break the ``gen_tokens.yml`` into ``gen_master_tokens`` and ``gen_node_tokens`` instead? Still, the task is meant to be run on master. Delegation of it should make it so.

[1] https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes/tasks/gen_tokens.yml

**Comment by aabed** [comment]
And then you include the gen_node_tokens in the node role instead of including the whole gen_token
I am a little rusty here I almost forgot what was this all about :smile:

**Comment by ingvagabund** [comment]
The task has to be run on the master. Since all the tokens are stored under ``/etc/kubernetes/tokens/known_tokens.csv``. Not so familiar with the tokens work-flow but I would say apiserver needs the file (just guessing).

**Comment by aabed** [comment]
yes, I know but you want it to be included and delegated, am I right?

**Comment by ingvagabund** [comment]
Still have not come with a plan :D But yes, it make sense to put it there. And it would solve the problem. You can try it and let me know :P

**Comment by ingvagabund** [comment]
@adamschaub what about generating tokens for HA? Will it be the same or will it require additional modification?

**Comment by aabed** [comment]
I think if I am going to do it it will be something like

in **secrets.yml**
```
- include: gen_node_tokens.yml
  when: inventory_hostname in groups['nodes']
```

in **gen_node_tokens.yml**

```
- name: Generate tokens for node components
  command: "{{ kube_script_dir }}/kube-gen-token.sh {{ item[0] }}-{{ item[1] }}"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
  with_nested:
    - [ 'system:kubelet', 'system:proxy' ]
    - "{{ groups['nodes'] }}"
  register: gentoken
  delegate_to: "{{ groups['masters'][0] }}"
  changed_when: "'Added' in gentoken.stdout"
  notify:
    - restart daemons

```
