### ISSUE TITLE
GLBC - Issues about effectively replace / updating a certificate

### ISSUE THREAD

**Issue by andreassolberg** [kubernetes/contrib#1396]
I've successfully managed to setup an ingress with a certificate. However, I have not yet found a way to reliably replace the certificate on the ingress.

The documentation at:
- https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce

does not mention updating or replacing certificates. I would suggest that a section is added to cover this.

I expected that when I replace the cert secret, and applied an replacement to the ingress object with a minor change (in example a route change), it would fetch the updated certs. This did not seem to happen.

Deleting the ingress, and recreating it did partly work, but creates severe downtime. I think that when creating the ingress with the same name, the old cert is cached/user. 

Right now, I need to deploy a new ingress with a new ID in parallell, getting a new IP, and switch in DNS, before phasing out the old one. Very cumbersome.

**Comment by bprashanth** [comment]
Hmm, this should work. We have an e2e for it (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/ingress_utils.go#L108). Are you running in GCE or GKE? What version Kubernetes? 

I just tried and it does what I expect. Upon apply, you should see a second ssl cert, i.e: 
```
$ gcloud compute ssl-certificates list 
NAME                                                       CREATION_TIMESTAMP
k8s-ssl-default-echomap--d1834d65b5c525fd                  2016-10-21T15:23:56.041-07:00
$ kubectl apply -f /tmp/foo2.yaml


... wait a bit ...
 
$ gcloud compute ssl-certificates list 
NAME                                                       CREATION_TIMESTAMP
k8s-ssl-1-default-echomap--d1834d65b5c525fd                2016-10-21T14:57:55.856-07:00
```

And on re-apply you should see it go back to the original name. 
This is because edits to the resource arean't allowed, and we can't delete the cert while it's in use, so we need to create a side-cert (-1), and atomically swap it before deleting the old one, then repeat every time the secret changes. 

There will be some delay in noticing the modified secret, because we're polling on secrets not watching, but it should work out. If you can give me repro steps I'll debug.

**Comment by svda** [comment]
I have similar issues using Kubernetes 1.4.3. Unfortunately I am unable to upgrade the cluster at the moment because of the downtime, so if this has been fixed in a recent version I apologize beforehand.

These are my yaml's:

secrets.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: tls-crt
  namespace: production
type: Opaque
data:
  tls.crt: <chain crt>
  tls.key: <private key>
```

load-balancer.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: load-balancer
  namespace: production
  labels:
    tier: backend
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: tls-crt
  backend:
    serviceName: api
    servicePort: 80
  rules:
  - host: api.<domain>.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: api
          servicePort: 80
  - host: developer.<domain>.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: developer
          servicePort: 80
```

When I update the base64 certificate string and update the secrets using kubectl update -f ./secrets.yaml, I get events with the following:

```
2016-10-31 10:44:00 +0100 CET   2016-10-30 20:06:52 +0100 CET   948       load-balancer   Ingress             Warning   GCE       {loadbalancer-controller }   googleapi: Error 409: The resource 'projects/<project_id>/global/sslCertificates/k8s-ssl-1-production-load-balancer--9aa517b40f2ca4ca' already exists, alreadyExists
```

Updating the load-balancer Ingress doesn't seem to have any effect either.
