### ISSUE TITLE
nginx ingress high latency / low rps vs service

### ISSUE THREAD

**Issue by foolusion** [kubernetes/contrib#1482]
calling via internal aws elb

    Running` 30s test @ http://elwin.k8s-a.ttoapps.aws.cloud.nordstrom.net/?userid=mm&teamid=test
      500 goroutine(s) running concurrently
    50085 requests in 30.16710187s, 17.19MB read
    Requests/sec:           1660.25
    Transfer/sec:           583.49KB
    Avg Req Time:           301.159048ms
    Fastest Request:        87.959178ms
    Slowest Request:        1.559768394s
    Number of Errors:       0

vs

calling via service

    Running 30s test @ http://elwin/?userid=mm&teamid=test
      500 goroutine(s) running concurrently
    3742341 requests in 29.776728744s, 1.09GB read
    Requests/sec:           125680.06
    Transfer/sec:           37.64MB
    Avg Req Time:           3.978355ms
    Fastest Request:        76.667µs
    Slowest Request:        410.97233ms
    Number of Errors:       0

calling via http-router with header Host: elwin.k8s-a.ttoapps.aws.cloud.nordstrom.net

    Running 30s test @ http://25.0.0.20/?teamid=test&userid=mm
      500 goroutine(s) running concurrently
    47453 requests in 30.1639595s, 16.29MB read
    Requests/sec:        1573.17
    Transfer/sec:        552.87KB
    Avg Req Time:        317.829847ms
    Fastest Request:    16.719018ms
    Slowest Request:    895.236499ms
    Number of Errors:    0

I am adding a snapshot of my config files. To start the service from scratch i would run the following.

    kubectl create -f elwin-mongo.yaml
    kubectl create -f elwin-storage.yaml
    kubectl create -f elwin.yaml

to run the benchmark i run 

    kubectl create -f elwin-wrk.yaml

i think you would need to modify the ingress in `elwin.yaml` to whatever your host is.

The service code is available at https://foolusion/github.com/choices if you need it for any reason. Let me know if you would like me to run anything to check performance.

[config.zip](https://github.com/kubernetes/contrib/files/400601/config.zip)

**Comment by bprashanth** [comment]
what is 25.0.0.20? the perf regression between {internal elb/nginx} x service is alarming

**Comment by bprashanth** [comment]
@aledbf fyi

**Comment by foolusion** [comment]
@bprashanth  25.0.0.20 is the ip address of the service for http-router (nginx ingress) in my cluster.

**Comment by aledbf** [comment]
@foolusion I cannot reproduce this scenario.
Can you provide more information about your cluster?

**Followed Procedure:**

Install kubernetes in GCE
```
curl -sS https://get.k8s.io | bash
```

SSH master node
```
rm /etc/kubernetes/manifests/glbs.manifest
```

Install nginx ingress controller
```
kubectl create -f https://raw.githubusercontent.com/kubernetes/contrib/master/ingress/controllers/nginx/rc.yaml
```

remove the limits in elwin (the default nodes do not fullfil the requirements)

create a service (to not use an IP)
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-lb
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: nginx-ingress-lb
```

```
apiVersion: batch/v1
kind: Job
metadata:
  name: elwin-wrk
  labels:
    job: elwin-wrk
spec:
  template:
    metadata:
      name: elwin-wrk
    spec:
      containers:
        - name: elwin-wrk
          image: williamyeh/wrk:4.0.2
          command:
            - /usr/local/bin/wrk
            - -t2
            - -c500
            - -d30s
            - --latency
            - --header
            - "Host: elwin.k8s-a.ttoapps.aws.cloud.nordstrom.net"
            - "http://nginx-ingress-controller.default.svc.cluster.local/?teamid=test&userid=mm"
      restartPolicy: Never
```



```
old-mbp:config aledbf$ kubectl create -f elwin-wrk.yaml
job "elwin-wrk" created
old-mbp:config aledbf$ kubectl get pods
NAME                             READY     STATUS    RESTARTS   AGE
default-http-backend-0bzw6       1/1       Running   0          51m
elwin-2367609915-8w990           1/1       Running   1          25m
elwin-2367609915-oywo7           1/1       Running   0          25m
elwin-2367609915-xap85           1/1       Running   1          25m
elwin-storage-3259184487-vofkg   1/1       Running   0          25m
elwin-wrk-dk27d                  1/1       Running   0          11s
nginx-ingress-controller-ew75a   1/1       Running   0          51m
old-mbp:config aledbf$ kubectl logs -f elwin-wrk-dk27d
Running 30s test @ http://nginx-ingress-controller.default.svc.cluster.local/?teamid=test&userid=mm
  2 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   160.91ms   43.13ms 404.54ms   69.03%
    Req/Sec     1.55k   420.29     3.69k    68.90%
  92980 requests in 30.09s, 33.43MB read
Requests/sec:   3090.11
Transfer/sec:      1.11MB
old-mbp:config aledbf$ kubectl get svc nginx-ingress-controller
NAME                       CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
nginx-ingress-controller   10.0.94.232   <none>        80/TCP    23m
old-mbp:config aledbf$ kubectl delete jobs elwin-wrk
job "elwin-wrk" deleted
old-mbp:config aledbf$ # change nginx-ingress-controller.default.svc.cluster.local with the IP 10.0.94.232
old-mbp:config aledbf$ kubectl create -f elwin-wrk.yaml
job "elwin-wrk" created
old-mbp:config aledbf$ kubectl get pods
NAME                             READY     STATUS    RESTARTS   AGE
default-http-backend-0bzw6       1/1       Running   0          52m
elwin-2367609915-8w990           1/1       Running   1          27m
elwin-2367609915-oywo7           1/1       Running   0          27m
elwin-2367609915-xap85           1/1       Running   1          27m
elwin-storage-3259184487-vofkg   1/1       Running   0          27m
elwin-wrk-1i7n0                  1/1       Running   0          5s
nginx-ingress-controller-ew75a   1/1       Running   0          52m
old-mbp:config aledbf$ kubectl logs -f elwin-wrk-1i7n0
Running 30s test @ http://10.0.94.232/?teamid=test&userid=mm
  2 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   157.50ms   79.76ms 340.83ms   70.84%
    Req/Sec     1.59k   524.71     3.26k    66.56%
  95026 requests in 30.05s, 34.16MB read
Requests/sec:   3162.48
Transfer/sec:      1.14MB
```
