### ISSUE TITLE
HTTPS Ingress allows http

### ISSUE THREAD

**Issue by heroic** [kubernetes/contrib#1517]
I have a inges.yaml defined like so:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: my-app
  rules:
  - host: t.my-app.com
    http:
      paths:
      - backend:
          serviceName: my-app
          servicePort: 80
```

This is as per the readme in the GCE https load balancer example. However, I still see an open http and https port. As seen here:

```
Name:           my-app
Namespace:      default
Address:        130.xxx.xxx.217
Default backend:    default-http-backend:80 (10.4.0.4:8080)
TLS:
  tls-cert terminates 
Rules:
  Host      Path    Backends
  ----      ----    --------
  t.my-app.com  
                backendSrv:80 (<none>)
Annotations:
  https-forwarding-rule:    k8s-fws-default-my-app--3332235f0ec32c08
  https-target-proxy:       k8s-tps-default-my-app--3332235f0ec32c08
  static-ip:            k8s-fw-default-my-app--3332235f0ec32c08
  target-proxy:         k8s-tp-default-my-app--3332235f0ec32c08
  url-map:          k8s-um-default-my-app--3332235f0ec32c08
  backends:         {"k8s-be-31461--3332235f0ec32c08":"HEALTHY","k8s-be-32348--3332235f0ec32c08":"HEALTHY"}
  forwarding-rule:      k8s-fw-default-my-app--3332235f0ec32c08
No events.
```

**Comment by aledbf** [comment]
@bprashanth ping

**Comment by bprashanth** [comment]
@heroic did you create the ingress with the annotation or update it? 
I just tried with an ingress like: 
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: bprashanth/echoserver:0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
data:
  tls.crt: <crt>
  tls.key: <key>
kind: Secret
metadata:
  name: tls-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: echoheaders-https
  labels:
    app: echoheaders-https
spec:
  type: NodePort
  ports:
  - port: 80
    # This port needs to be available on all nodes in the cluster
    nodePort: 30301
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders-https
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders-https
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: echoheaders-https
    spec:
      containers:
      - name: echoheaders-https
        image: gcr.io/google_containers/echoserver:1.3
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoheaders
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: tls-secret
  rules:
  - host: foobar.com
    http:
      paths:
      - backend:
          serviceName: echoheaders-https
          servicePort: 80
```
and got
```
TLS:
  tls-secret terminates 
Rules:
  Host		Path	Backends
  ----		----	--------
  foobar.com	
    		 	echoheaders-https:80 (<none>)
Annotations:
  backends:			{"k8s-be-30301--26c9e835d1cdce19":"HEALTHY","k8s-be-31710--26c9e835d1cdce19":"HEALTHY"}
  https-forwarding-rule:	k8s-fws-default-echoheaders--26c9e835d1cdce19
  https-target-proxy:		k8s-tps-default-echoheaders--26c9e835d1cdce19
  url-map:			k8s-um-default-echoheaders--26c9e835d1cdce19
Events:

```
