### ISSUE TITLE
Nginx ingress with https

### ISSUE THREAD

**Issue by scheeles** [kubernetes/contrib#1525]
The nginx ingress don't accept the same tls format as the GCE.

For nginx the host must be every time specified min the tls definition:

```
spec:
  tls:
  - hosts:
    - foo.bar.com
    secretName: foo-secret
```

this ingress don't serve https on nginx:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: no-rules-map
spec:
  tls:
    - secretName: testsecret
  backend:
    serviceName: s1
    servicePort: 80
```

but it work for GKE and also mention here http://kubernetes.io/docs/user-guide/ingress/
