### ISSUE TITLE
Validate SSL certificates when downloading binaries

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/contrib#1544]
Kubernetes, flannel, etcd and possibly other component have their corresponding binaries downloaded without SSL certs validation. The validation should be at least configurable. Opening the issue so we can talk about it and solve it eventually. E.g.

``` yaml
- name: Download Kubernetes binaries
  get_url:
    url: "{{ kube_download_url_base }}/{{ item }}"
    dest: "{{ kube_current_release_directory }}/{{ item }}"
    mode: 0755
    validate_certs: False
```
