### ISSUE TITLE
Nginx Ingress controller default backend

### ISSUE THREAD

**Issue by wernight** [kubernetes/contrib#1590]
I noticed on https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx that you advice to explicitely specify the default backend. Why do that instead of using the Ingress defined default backend?

```
kind: Ingress
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
```

Also, why is returning an HTTP 404 a requirement? Shouldn't that be up to the website to decide how to respond to unknown subdomains?
