### ISSUE TITLE
missing proxy environment settings in ansible roles

### ISSUE THREAD

**Issue by k3vinha** [kubernetes/contrib#1728]
missing proxy configuration for yum module in the following files:
ansible/roles/docker/tasks/install-rpms.yml
ansible/roles/master/tasks/install_rpms.yml
ansible/roles/master/tasks/pkgMgrInstallers/centos-install.yml
ansible/roles/node/tasks/install_rpms.yml
ansible/roles/node/tasks/pkgMgrInstallers/centos-install.yml

need to add the following lines for yum in files mentioned:
```
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
```
