### ISSUE TITLE
Name-based Vhosts in Nginx Ingress Errors out

### ISSUE THREAD

**Issue by alph486** [kubernetes/contrib#1761]
When using the current `nginx-alpha` ingress controller and the following ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: my-ns
spec:
  rules:
  - host: myservice.domaon.name
    http:
      paths:
      - backend:
          serviceName: svc-planner
          servicePort: 3000
```

The following error occurs in the ingress controller:

```
2016/09/20 16:48:14 Failed to execute nginx -s reload: nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:13
, err: exit status 1
```

This also occurs with multiple backends.
