### ISSUE TITLE
ingress: implement --watch-namespaces and --ignore-namespaces in nginx controller

### ISSUE THREAD

**Issue by kayrus** [kubernetes/contrib#1770]
current `--watch-namespace` implementation doesn't work well.
- first of all you can specify only one namespace or all namespaces.
- when you already have system namespaces (i.e. monitoring, kube-system, etc.) along with several production namespaces, it is not possible to schedule ingress controller which will serve only production namespaces (because we can schedule only one ingress controller per node)

`--ignore-namespaces` will be suitable for system namespaces (blacklist). `--watch-namespaces` will be suitable for production namespaces (whitelist).

Also I suppose this could be implemented inside configmaps and won't require ingress controller restart (since daemonsets don't support rolling update).

**Comment by kayrus** [comment]
Looks like duplicate of #847

**Comment by nikitswaraj12345** [comment]
I have created two different namespaces for different environment. one is devops-qa and another is devops-dev. I created two ingress in different namespaces. So while creating ingress of qa env in devops-qa namespace, the rules written inside ingress of qa is working fine. Means I am able to access the webpage of qa env. The moment I will create the ingress of dev env in devops-dev namespace, I will be able to access the webpage of dev env but wont be able to access the webpage of qa. And when I delete the dev ingress then again I will be able to access the qa env website

Below is the ingree of both dev and qa env.

**Dev Ingress**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-dev
  namespace: devops-dev
spec:
  tls:
  - hosts:
    - cafe.example.com
    secretName: default-token-jhtx3
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: miqpdev-svc
          servicePort: 80
```
**QA Ingress**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-qa
  namespace: devops-qa
spec:
  tls:
  - hosts:
    - cafe.example.com
    secretName: default-token-bjg3z
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /greentea
        backend:
          serviceName: greentea-svc
          servicePort: 80
      - path: /blackcoffee
        backend:
          serviceName: blackcoffee-svc
          servicePort: 80
```
The token mentioned in the ingress file is of each namespace. How can i run both the ingress and will be able to get all the websites deployed in both dev and qa env ?
