### ISSUE TITLE
Allow mixed http / https GCLB Ingress rules

### ISSUE THREAD

**Issue by svda** [kubernetes/contrib#1791]
I have an ingress fanout running with two https services, but I would like to add a third one using http only. This is impossible in the current config, which is as follows:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: load-balancer
  # namespace: production
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: myservice-tls
  backend:
    serviceName: api
    servicePort: 80
  rules:
  - host: api.myservice.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: api
          servicePort: 80
  - host: developer.myservice.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: developer
          servicePort: 80
```

Something more flexible should be implemented, for example allowing annotations inside fanout rules. Not sure if this is possible, but this would also open the door to add http > https redirects, multi-tls (like https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/multi-tls/multi-tls.yaml), etc.
