### ISSUE TITLE
[nginx-ingress-controller] Proxy protocol example has bug in health check

### ISSUE THREAD

**Issue by emmanuel** [kubernetes/contrib#1795]
It appears that the proxy protocol setting (set via configmap) breaks the default health check. Nginx is expecting PROXY protocol on the default HTTP port, but the kubelet is just speaking plain HTTP. The 18080 port looks expressly designed for this purpose, so I was able to get things working merely by switching the readiness/liveness probe config to look like the following:

``` yaml
          readinessProbe:
            httpGet:
              path: /healthz
              port: 18080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 18080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
```
