### ISSUE TITLE
[kube-keepalived-vip] don't start error

### ISSUE THREAD

**Issue by yolkov** [kubernetes/contrib#1821]
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: 3 baremetal nodes
- **OS** (e.g. from /etc/os-release): debian jessie
- **Kernel** (e.g. `uname -a`): Linux avi-app68 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
- **Install tools**:  kubelet as systemd service, others from manifests pods
- **Others**: calico network

vip-daemonset.yaml
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-keepalived-vip
spec:
  template:
    metadata:
      labels:
        name: kube-keepalived-vip
    spec:
      hostNetwork: true
      #nodeSelector:
      #  type: worker
      volumes:
        - name: modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
      containers:
        - image: gcr.io/google_containers/kube-keepalived-vip:0.8
          name: kube-keepalived-vip
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /dev
              name: dev
          # use downward API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          # to use unicast
          args:
          - --services-configmap=kube-system/vip-configmap
```

vip-configmap.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vip-configmap
data:
  10.9.1.70: demos/service-example
```

10.9.1.70 - free ip from host network

kubectl logs po/kube-keepalived-vip-8xjnx:
```
F1002 20:05:34.704159       1 controller.go:299] Error getting POD information: timed out waiting to observe own status as Running
goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0x33b6500, 0x0, 0x0, 0x0)
        /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xb8
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x3396180, 0xc800000003, 0xc82050ef00, 0x3360868, 0xd, 0x12b, 0x0)
        /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x259
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x3396180, 0x3, 0x26159a0, 0x21, 0xc82042fc48, 0x1, 0x1)
        /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x1d4
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x26159a0, 0x21, 0xc82042fc48, 0x1, 0x1)
        /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x5d
main.newIPVSController(0xc8203f0a80, 0x0, 0x0, 0x1ce0700, 0x7ffcd19a2c48, 0x19, 0xc8203eb628)
        /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/controller.go:299 +0x2a7
main.main()
        /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/main.go:115 +0x812
```
