### ISSUE TITLE
Custom IP with GLBC doesn't work

### ISSUE THREAD

**Issue by javiercr** [kubernetes/contrib#1857]
I'm trying to create an ingress with an IP previously created from the Google Cloud console, following the [instructions](https://gist.github.com/bprashanth/545f00b3b5488109c727) by @bprashanth :

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: another-no-rules-map
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "staticip"
spec:
  tls:
  - secretName: testsecret
  backend:
    serviceName: haproxy
    servicePort: 80
```

Where `staticip` it's the name of the IP I created from the console. The annotation works (it gets added to the Ingress resource) however kubernetes totally ignores it and allocates a new IP. I also tried with `ingress.kubernetes.io/global-static-ip-name` as the annotation name but it didn't work.

Am I missing something or is this behavior broken?

In case it helps, here is the version I'm running:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

This behavior was introduced in PR #563.
