### ISSUE TITLE
TLS auth for nginx-controller

### ISSUE THREAD

**Issue by dshmelev** [kubernetes/contrib#1870]
How can I implement mutual tls auth on nginx-controller?
Example:

```
ssl_certificate /etc/nginx-ssl/ca.crt;
ssl_certificate_key /etc/nginx-ssl/api-api.pem;
ssl_client_certificate /etc/nginx-ssl/api-api.pem;
ssl_verify_client on;
```

I put ca.crt to ingress secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: api-search
  namespace: api-search
data:
  tls.crt: base64 string
  tls.key: base64 string
  ca.crt: base64 string
```

but `/etc/nginx-ssl/api-api.pem` file not contain ca.crt.
Thank you.
