### ISSUE TITLE
[nginx-ingress-lb] Error syncing pod, skipping: failed to "StartContainer" for "nginx-ingress-lb"

### ISSUE THREAD

**Issue by alfirin** [kubernetes/contrib#1872]
I deployed a new v1.4.1 kubernetes cluster.

I follow the tutorial to create nginx-ingress-lb.

When I do the containers always restarting with some errors: 
`Readiness probe failed: HTTP probe failed with statuscode: 404`
or: `Liveness probe failed: HTTP probe failed with statuscode: 404`
or: `Back-off restarting failed docker container `
or: `Error syncing pod, skipping: failed to "StartContainer" for "nginx-ingress-lb" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=nginx-ingress-lb pod=nginx-ingress-controller-8ahmm_kube-system(d252e1a9-8fcc-11e6-8e94-028069efceb3)"`

With a lot of restarts.

<img width="1104" alt="screen shot 2016-10-12 at 00 11 27" src="https://cloud.githubusercontent.com/assets/2813035/19290624/e8a97524-9010-11e6-9c96-00ac7ce0aa13.png">

**Comment by aledbf** [comment]
@alfirin please check the probe URL is `/healthz` and the port `10254`

**Comment by alfirin** [comment]
@aledbf: Thanks.

I did what you told me and it worked.

Do you think I should create a PR in order to update [this example](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/default/rc-default.yaml) which is obviously not working.

For the others, this is my RC for the nginx-ingress-controller:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
        name: nginx-ingress-lb
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
```
