### ISSUE TITLE
[NGINIX Ingress Controller] Support for 301 redirects.

### ISSUE THREAD

**Issue by MaikuMori** [kubernetes/contrib#1884]
Would be nice to be able to setup 301 redirects. As services come and go, certain things in the cluster get deprecated and require a redirect to a new location. 

Two current solutions that I'm aware of now:
- Use custom template, but this is overkill and makes upgrading controller harder/error prone;
- Put another proxy in front of the ingress controller, also seems overkill, but maybe not a bad idea in longterm
- Spin up container which only does redirection for configurable domains. (This is what I'll currently use until there is a better solution)

The general issue is to be able to add custom configuration sections in global and per ingress controller scope. Otherwise I feel the project will end up slowly implementing each NGINX config option as flag.

I am willing to contributing the redirect code.

**Comment by aledbf** [comment]
@MaikuMori can you post an Ingress rules as example?

**Comment by MaikuMori** [comment]
Could be done with some awkward Ingress rule like this:

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: test
  annotations:
    ingress.kubernetes.io/301-to: "https://domain.com/path"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: foo.bar.com
```

Other option is in the configmap using some sort of format:

```
301-redirects: "foo.bar.com:https://domain.com/path boo.bar.com:https://other.com/"
```
In this example split on ` ` and then on first `:`. I'm sure there is a better separator choice.

Personally I would like free-form config map entry like:
```
global-block: |
  some_other_custom_option set-to-value;
  server {
	listen 80;
	server_name foo.bar.com;
	return 301 $scheme://domain2.com$request_uri;
  }
```

Also such custom block set via annotations would be nice for adding custom options to server directives created by Ingress resource.

@aledbf what do you think?
