### ISSUE TITLE
Create a scheduled job using the API

### ISSUE THREAD

**Issue by PierrickI3** [kubernetes/contrib#1948]
Using minikube 0.12.0

I am trying to create a scheduled job using the API (via kubectl proxy):

`curl -X POST http://localhost:8001/apis/batch/v2alpha1/scheduledjobs -d @testscheduledjob.yaml -H 'Content-type:application/yaml'`

Contents of testscheduledjob.yaml:

```
apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: hello
spec:
  schedule: 0/1 * * * ?
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

I get this error:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {},
  "code": 405
}
```

Is there a way to create a scheduled job other than using `kubectl` at the moment?
