### ISSUE TITLE
[Nginx ingress controller] Ability to exclude routes from auth

### ISSUE THREAD

**Issue by kop** [kubernetes/contrib#1950]
A little proposal for the authentication system.

It would be very helpful to have an ability to set a list of URI's (or a list of regular expressions) that should not use authentication system (both basic and external).

For example, in my current scenario, I need to limit access to our internal cluster services for users, but still be able to accept webhooks from third party systems.

**Comment by aledbf** [comment]
@kop you can do that now creating two ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-url: https://httpbin.org/basic-auth/user/passwd
  name: foo
  namespace: default
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: echoheaders-x
          servicePort: 80
        path: /

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-noauth
  namespace: default
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: echoheaders-x
          servicePort: 80
        path: /webhooks        
```
