### ISSUE TITLE
DaemonSet not exposing hostPort correctly.

### ISSUE THREAD

**Issue by hsyed** [kubernetes/contrib#1963]
I'm trying to get the DaemonSet example working. port 80 and 443 cause collisions on 4/6 nodes resulting in the controllers not comping up. Switching to 81 and 844 brings the controllers up but the ports aren't available on the nodes. Switching to `hostNetwork` does lead to 2/6 working controllers -- if I could find a way of mapping the ports I'd be happy.

The example leads me to believe DaemonSet should be mapping the ports. Is this a bug ?

I'm running on AWS in a 3x AZ HA config with weavenet. 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dev-services-lb
  namespace: dev-services
spec:
  template:
    metadata:
      labels:
        name: dev-services-lb
    spec:
#      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
        name: dev-services-lb
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 81
        - containerPort: 443
          hostPort: 444
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
```
