### ISSUE TITLE
[ansible] ansible fails with 'kube_binaries' is undefined when using packageManager on fedora 24

### ISSUE THREAD

**Issue by ObviusOwl** [kubernetes/contrib#2026]
Hi,
I'm on a fully updated fresh install of fedora 24. The configuration is almost default except enabled kube-ui and kube-dash.

Ansible fails with:

```
TASK [master : Set a list of kube master binaries to download] *****************
skipping: [kube-master.example.com] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [master : Extend the list of kube master binaries with kubelet] ***********
skipping: [kube-master.example.com] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [master : Download Kubernetes binaries] ***********************************
fatal: [kube-master.example.com]: FAILED! => {"failed": true, "msg": "'kube_binaries' is undefined"}
	to retry, use: --limit @/root/contrib/ansible/playbooks/deploy-cluster.retry
```

Deleting the content in `roles/master/tasks/download_bins.yml` helps.

The same applies for `roles/master/tasks/install_rpms.yml` where ansible complains about undefined `kube_rpms` (logs not included for brevity)

Deleting the content of the files still provides a working set-up, since the packages are in fact installed correctly and thus don't need external rpm's or github release.

Maybe this is a issue with ansible not ignoring correctly the tasks, unfortunately I'm completely new to ansible.

**Comment by lvnilesh** [comment]
I see similar failure

    ./deploy-cluster.sh --tags=masters -vvv 

```
TASK [master : Download Kubernetes binaries] ***********************************
task path: /Users/cloudgenius/contrib/ansible/roles/master/tasks/download_bins.yml:17
fatal: [192.168.122.22]: FAILED! => {
    "failed": true, 
    "msg": "'kube_binaries' is undefined"
}
```

**Comment by ingvagabund** [comment]
@ObviusOwl, @lvnilesh what is your version of ansible?

**Comment by ingvagabund** [comment]
Most likely related to this: https://github.com/ansible/ansible/issues/14201

**Comment by ObviusOwl** [comment]
My ansible version is 2.2.0.0, the issue mentioned seems to get fixed in 2.2.0.0-1

**Comment by ingvagabund** [comment]
@ObviusOwl this needs to be fixed anyway based on the PR's comment.

I am not able to reproduce the scenario described in the PR with ansible-2.1.0.0-1.fc24.noarch. Testing with two files and localhost inventory:

```
---
- hosts: nodes
  tasks:
   - name: Detected version
     debug:
       msg: "Hey"

   - name: Include test
     include: tt.yml
     when: False
```

```
---
- name: Set a list of kube master binaries to download
  set_fact:
    kube_binaries: "test"
```

```
[masters]
localhost ansible_connection=local

[nodes]
localhost ansible_connection=local

[etcd]
localhost ansible_connection=local
```

Output:
```
$ ansible-playbook -i inventory/localhost.ini test.yml 

PLAY [nodes] *******************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Detected version] ********************************************************
ok: [localhost] => {
    "msg": "Hey"
}

TASK [Include test] ************************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

Based on the comment the ``ansible-2.1.0.0-1.fc24.noarch`` does not behave as it should.

@ObviusOwl, @lvnilesh can you run the provided tasks on your system and see if you can reproduce it again? If you, can you post precise version of your ansible (rpm -q ansible)?

**Comment by ingvagabund** [comment]
Running the same test with ``ansible-2.1.2.0-1.fc24`` and ``ansible-2.2.0.0-1.fc24``. Still have not been able to reproduce it.

**Comment by ingvagabund** [comment]
At the same time can you update ``Download Kubernetes binaries`` in ``roles/master/tasks/download_bins.yml`` like this?:

```
- name: Download Kubernetes binaries
  get_url:
    url: "{{ kube_download_url_base }}/{{ item }}"
    dest: "{{ kube_current_release_directory }}/{{ item }}"
    mode: 0755
    validate_certs: False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
  with_items:
    - "{{ kube_binaries }}"
  always_run: True
```

I have not found any mention of limitations of the ``always_run`` if it is limited to "dry run" only or applicable to skipped tasks as well.
