### ISSUE TITLE
[ingress] Path regex matching

### ISSUE THREAD

**Issue by soudy** [kubernetes/contrib#2027]
I was wondering about regex matching in Ingress paths like nginx does with `~`. For example, I'd like to be able to do something like this:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /user/*/tiles/
        backend:
          serviceName: specific
          servicePort: 80
      - path: /
        backend:
          serviceName: default
          servicePort: 80

```
And have /user/test/tiles/ go to the `specific` service. At the moment it will only literally match `/user/*/tiles`. I see [here](https://github.com/kubernetes/contrib/blob/494064ba4e685a3d9432411bcd72dc5d49641316/ingress/controllers/nginx/nginx.tmpl#L212) that `location =` is used, is it perhaps an idea to make this configurable? I found [this](http://stackoverflow.com/a/40026443) stackoverflow answer from 2013 in which the `~ path` syntax is used, which I assume was removed. 

Are there any plans on implementing this, and also, if it was removed, why so?
