### ISSUE TITLE
[Nginx ingress controller] Annotations configuration in ingress

### ISSUE THREAD

**Issue by timactive** [kubernetes/contrib#2044]
Add new anotations for nginx config in ingress

This annotation must override config in configmap.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: docker-registry
 namespace: devops
 annotations:
   ingress.kubernetes.io/cg-body-size: "600M"
   ingress.kubernetes.io/cg-server-name-hash-bucket-size: "64"
   ingress.kubernetes.io/cg-server-name-hash-bucket-size: "64"
spec:
  tls:
  - hosts:
    - registry.example.com
    secretName: registry-example-tls
  rules:
    - host: registry.example.com
      http:
        paths:
        - path: /
          backend:
            serviceName: docker-registry-sv
            servicePort: 5000
```
