### ISSUE TITLE
Ingress does not support several TLS certificates

### ISSUE THREAD

**Issue by ged15** [kubernetes/contrib#2058]
Firstly, thanks for the fantastic tool that is Kubernetes! Really helps me in a bunch of situations!
Are there any plans to make a single Ingress support several TLS certificates? Currently I can have an Ingress route traffic for several host names but I cannot have a TLS cert per hostname so I cannot configure one Ingress to route traffic for `example.com` and `example.org` with their own certificates.

**Comment by aledbf** [comment]
@ged15 please post the Ingress rules

**Comment by ged15** [comment]
Well let's take an example from the K8s documentation:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: s1
          servicePort: 80
  - host: bar.foo.com
    http:
      paths:
      - backend:
          serviceName: s2
          servicePort: 80
```

Now there does not seems to be a way for me to define 2 different TLS certificates - one for `foo.bar.com` and another one for `bar.foo.com`. Or am I missing something?
