### ISSUE TITLE
/usr/lib/tmpfiles.d not writable

### ISSUE THREAD

**Issue by lvnilesh** [kubernetes/contrib#2091]
three coreos instances accessible via ssh

inventory is like this:

```
[masters]
192.168.122.119 ansible_python_interpreter=/opt/bin/python

[etcd:children]
masters

[nodes]
192.168.122.226 ansible_python_interpreter=/opt/bin/python
192.168.122.231 ansible_python_interpreter=/opt/bin/python
192.168.122.119 ansible_python_interpreter=/opt/bin/python

```

I run ` ./deploy-cluster.sh` and run into this error. 

```
TASK [node : Get Systemd tmpfile from Kubernetes repository] *******************
skipping: [192.168.122.226]
skipping: [192.168.122.231]
fatal: [192.168.122.119]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /usr/lib/tmpfiles.d not writable"}
```

**Comment by lvnilesh** [comment]
five coreos instances 

```
[masters]
192.168.122.250 ansible_python_interpreter=/opt/bin/python

[etcd:children]
masters

[nodes]
192.168.122.82  ansible_python_interpreter=/opt/bin/python
192.168.122.129 ansible_python_interpreter=/opt/bin/python
192.168.122.250 ansible_python_interpreter=/opt/bin/python
192.168.122.172 ansible_python_interpreter=/opt/bin/python
192.168.122.200 ansible_python_interpreter=/opt/bin/python
```
same error.

```
TASK [node : Get Systemd tmpfile from Kubernetes repository] *******************
skipping: [192.168.122.82]
skipping: [192.168.122.129]
skipping: [192.168.122.172]
skipping: [192.168.122.200]
fatal: [192.168.122.250]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /usr/lib/tmpfiles.d not writable"}
```

**Comment by lvnilesh** [comment]
The error seems to occur only with the `master` node.

**Comment by ingvagabund** [comment]
Not sure how much is this issue related to CoreOS OS. Unfortunately, I don't have any CoreOS cluster available.  Depending on a distribution, ``/usr`` can be read only. So the error message for ``/usr/lib/tmpfiles.d`` makes sense. @danehans @stephenrlouie WDYT?

**Comment by lucas-cegatti** [comment]
I had the same problem in CoreOS, what happens is that the OS by default mounts the `/user` onto a read only partition, more info [here](https://coreos.com/os/docs/latest/sdk-disk-partitions.html).

The problem specifically is in `roles/node/tasks/retrieve-systemd-files.yml` task `Get Systemd tmpfile from Kubernetes repository` which tries to copy a file to `/usr/lib/tmpfiles.d/`.

What I did was ignore the first task on CoreOS and I also added another task (for CoreOs only) to copy that file into `/run/tmpfiles.d` which will have the same effect and is not mounted on a read only partition. 

```yaml
- name: Get Systemd tmpfile from Kubernetes repository
  get_url:
    url=https://raw.githubusercontent.com/kubernetes/contrib/master/init/systemd/tmpfiles.d/kubernetes.conf
    dest=/usr/lib/tmpfiles.d/kubernetes.conf
    force=yes
  notify:
    - reload systemd
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
  when: not is_coreos

- name: CoreOS | Get Systemd tmpfile from Kubernetes repository
  get_url:
    url=https://raw.githubusercontent.com/kubernetes/contrib/master/init/systemd/tmpfiles.d/kubernetes.conf
    dest=/run/tmpfiles.d/kubernetes.conf
    force=yes
  notify:
    - reload systemd
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
  when: is_coreos
```
