### ISSUE TITLE
[Nginx ingress controller] Downtime of service exposed via Ingress while doing upgrade.

### ISSUE THREAD

**Issue by AlexRRR** [kubernetes/contrib#2098]
Test System:
- Baremetal CoreOS
- Network: Flannel
- K8s 1.4.6
- nginx-ingress-controller:0.8.3 

## Steps to reproduce
create a `Deployment` consisting of a simple service like a bare nginx
```yaml
apiVersion: extensions/v1beta1                                                      
kind: Deployment                                                                    
metadata:                                                                           
  name: weather-app                                                                 
spec:                                                                               
  replicas: 3                                                                       
  strategy:                                                                         
    rollingUpdate:                                                                  
      maxSurge: 1                                                                   
      maxUnavailable: 1                                                             
  template:                                                                         
    metadata:                                                                       
      labels:                                                                       
        app: weather-app                                                            
        track: stable                                                               
        attempt: "1"                                                                
    spec:                                                                           
      containers:                                                                   
      - name: weather-app                                                           
        lifecycle:                                                                  
            preStop:                                                                
                exec:                                                               
                    command: ["/usr/sbin/nginx","-s","quit"]                        
        image: nginx:latest                                                         
        ports:                                                                      
        - containerPort: 80                                                         
        imagePullPolicy: Always                                                     
        readinessProbe:                                                             
          httpGet:                                                                  
            path: /                                                                 
            port: 80                                                                
          failureThreshold: 3                                                       
          successThreshold: 1                                                       
          periodSeconds: 5                                                          
          timeoutSeconds: 1                                                         
          initialDelaySeconds: 0                                                    
        livenessProbe:                                                              
          httpGet:                                                                  
            path: /                                                                 
            port: 80                                                                
          failureThreshold: 3                                                       
          successThreshold: 1                                                       
          periodSeconds: 10                                                         
          timeoutSeconds: 1                                                         
          initialDelaySeconds: 15 
``` 
Service
```yaml
apiVersion: v1                                                       
kind: Service                                                        
metadata:                                                                            
  labels:                                                            
    app: weather-app                                                 
  name: weather-app                                                  
  namespace: k8-demo                                                 
  clusterIP: 10.3.0.47                                               
  ports:                                                             
  - port: 80                                                         
    protocol: TCP                                                    
    targetPort: 80                                                   
  selector:                                                          
    app: weather-app                                                 
  sessionAffinity: None                                              
  type: ClusterIP                                                    
```

Ingress Resource
```yaml
apiVersion: v1                                                                           
items:                                                                                   
- apiVersion: extensions/v1beta1                                                         
  kind: Ingress                                                                          
  metadata:                                                                                                                                             
    name: weather-demo                                                                   
    namespace: k8-demo                                                                            
  spec:                                                                                  
    rules:                                                                               
    - host: weather-demo.internal.ch                                                
      http:                                                                              
        paths:                                                                           
        - backend:                                                                       
            serviceName: weather-app                                                     
            servicePort: 80                                                              
          path: /                                                                                                                                                                                           
```

Perform update by simply increasing the `attempt`  label, and `kubectl apply -f deploy.yaml`
while in a terminal fetching the NGINX web page every second with `watch -n "curl http://weather-demo.internal.ch"`

## Expected results

The Deployment is updated with no downtime

## Actual results

- New pods are created
- Old pods are deleted once new ones have `Running` state 
- New pods answer 
- URL returns a *504* Error from NGINX resource controller for a few seconds
- Service reestablished.

If at the same time I expose the service via NodePort and curl there, the service is *always* available.
