### ISSUE TITLE
service-loadbalancer : udp support

### ISSUE THREAD

**Issue by gregbkr** [kubernetes/contrib#2133]
Hello,

I am using rc.yaml to redirect tcp and udp query to ELK.
tpc seems fine: I can access kibana and send logs via tcp
udp doesn't foward. I can send logs ok in the container, or to the svc_ip. But not throught the loadbalancer.

Which arg should I use in the lb?
      args:
        - --udp-services=logstash:5000 ?

I tried but not luck:
        args:
        - --tcp-services=kibana:5601,logstash:5001,logstash:5000 

I test with:
```
kubectl exec logstash -- bash -c "echo test | socat -t 0 - UDP:10.0.252.166:5000"   <-- svc_ip : ok
kubectl exec logstash -- bash -c "echo test | socat -t 0 - TPC:10.0.252.166:5001"   <-- svc_ip: ok

echo testudp | socat -t 0 - UDP:185.19.30.194:5000   <-- nok
echo testtcp | socat -t 0 - TCP:185.19.30.194:5001    <-- ok
```

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: service-loadbalancer
  labels:
    app: service-loadbalancer
    version: v1
spec:
  replicas: 1
  selector:
    app: service-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: service-loadbalancer
        version: v1
    spec:
      nodeSelector:
        role: loadbalancer
      containers:
      - image: gcr.io/google_containers/servicelb:0.4
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
        ## All http services
        # kibana
        - containerPort: 5601
          hostPort: 5601
          protocol: TCP
        # logstash UDP (syslog)
        - containerPort: 5000
          hostPort: 5000
          protocol: UDP
        # logstash TCP (filebeat)
        - containerPort: 5001
          hostPort: 5001
          protocol: TCP
        resources: {}
        args:
        - --tcp-services=kibana:5601,logstash:5001
        - --udp-services=logstash:5000    #<-- I guessed here, I couldn't find any arg reference....
```

Thank you for your help!
Greg.
