### ISSUE TITLE
Sample still not working 

### ISSUE THREAD

**Issue by iamnewspecies** [kubernetes/contrib#2143]
I followed the instructions on how to configure config-map for TCP routing. But I am still not successful!

[https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/tcp](instructions)

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-configmap-example
data:
  2776: "default/example-go:8080"
```

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
        name: nginx-ingress-lb
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        # service echoheaders as TCP service default/echoheaders:9000
        # 9000 indicates the port used to expose the service
        - containerPort: 2776
          hostPort: 2776
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-configmap-example
```

Following is the ouput of **kubectl describe svc kubernetes**:

Name:           kubernetes
Namespace:      default
Labels:         component=apiserver
            provider=kubernetes
Selector:       <none>
Type:           NodePort
IP:         10.0.0.1
Port:           https   443/TCP
NodePort:       https   31261/TCP
Endpoints:      10.0.2.15:443
Port:           telco-smpp  2776/TCP
NodePort:       telco-smpp  31483/TCP
Endpoints:      10.0.2.15:2776
Port:           telco-https 8444/TCP
NodePort:       telco-https 31225/TCP
Endpoints:      10.0.2.15:8444
Session Affinity:   ClientIP

Following is the ouput of **kubectl describe endpoints**:

Name:       kubernetes
Namespace:  default
Labels:     <none>
Subsets:
  Addresses:        10.0.2.15
  NotReadyAddresses:    <none>
  Ports:
    Name    Port    Protocol
    ----    ----    --------
    https   443 TCP
    telco-https 8444    TCP
    telco-smpp  2776    TCP

What am I doing wrong?
