### ISSUE TITLE
nginx-ingress-controller: Route By Query String 

### ISSUE THREAD

**Issue by TWood67** [kubernetes/contrib#2148]
I'm looking for the ability to route traffic via query string. We have a bucketed system that supports session persistence with either a query string or cookie. We are currently able to achieve this with HAProxy and ACL url_param. The idea is that I specify a field and a value in my ingress resource and any requests with the matching field and value are routed to the specified service.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      fields:
      - <fieldKey>: <fieldValue>
        backend:
          serviceName: s1
          servicePort: 80
```
Is this something nginx can support? I would be more than happy to work on a PR for this change if so.
