### ISSUE TITLE
[ingress] Multi TLS working incorrectly

### ISSUE THREAD

**Issue by soudy** [kubernetes/contrib#2153]
I was trying to achieve SNI using the example described [here](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/multi-tls). However, with 2 domains, only one of them worked, because all domains were using the same certificate. The ingress config I used looks like this:

```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: frontend-proxy
spec:
  tls:
  - hosts:
    - foo.com
    secretName: foo.com
  - hosts:
    - foo.nl
    secretName: foo.nl

  rules:
  - host: foo.com
    http:
      paths:
      - backend:
          serviceName: frontend-proxy
          servicePort: 80

  - host: foo.nl
    http:
      paths:
      - backend:
          serviceName: frontend-proxy
          servicePort: 80
```

This resulted in both `foo.com` and `foo.nl` using the `foo.com` certificate. Is there anything I'm doing wrong that I'm missing, or is this a bug?
