### ISSUE TITLE
cluster-autoscaler: multiple instances in different AZs are in fight for leader

### ISSUE THREAD

**Issue by rimusz** [kubernetes/contrib#2163]
I have three AWS ASG, did setup three separate cluster-autoscaler deployments with different names and namespaces, even then I see errors from two scalers:
```
cluster-scaler-azc-126014070-t3ky3 cluster-scaler-azc I1216 17:18:27.235227       1 leaderelection.go:210] failed to renew lease kube-system/cluster-autoscaler
cluster-scaler-azc-126014070-t3ky3 cluster-scaler-gen-azc I1216 17:18:27.235205       1 leaderelection.go:295] lock is held by cluster-scaler-azb-3625505393-a3n2b and has not yet expired
```

Why all of them checking for the lock `kube-system/cluster-autoscaler`?
Is any extra parameter needs to be used there?

**Comment by tylernm14** [comment]
I'm experiencing the same issue with two auto scaling groups in the same AWS AZ.

**Comment by ideahitme** [comment]
@tylernm14 yes, this is the problem with hardcoded namespace/name. Might be partially addressed in this PR: https://github.com/kubernetes/contrib/pull/2226

**Comment by tylernm14** [comment]
@rimusz I was able to get around this problem by putting a '--nodes' entry for each ASG in the command line invocation of cluster-autoscaler
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  labels:
    k8s-app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cluster-autoscaler
  template:
    metadata:
      labels:
        k8s-app: cluster-autoscaler
    spec:
        containers:
          - name: cluster-autoscaler
            image: gcr.io/google_containers/cluster-autoscaler:v0.3.0
            resources:
              limits:
                cpu: 100m
                memory: 300Mi
              requests:
                cpu: 100m
                memory: 300Mi
            command:
              - ./cluster-autoscaler
              - --v=4
              - --skip-nodes-with-local-storage=false
              - --cloud-provider=aws
              - --nodes=2:16:red-nodes.example.com
              - --nodes=4:16:blue-nodes.example.com
            env:
              - name: AWS_REGION
                value: us-east-1
            volumeMounts:
              - name: ssl-certs
                mountPath: /etc/ssl/certs/ca-certificates.crt
                readOnly: true
        volumes:
          - name: ssl-certs
            hostPath:
              path: /etc/ssl/certs/ca-certificates.crt
```
