### ISSUE TITLE
[ansible] Insure PyYAML module is installed for the master role.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/contrib#2178]
From kubernetes/kubernetes#37352.

A user was using the ansible repo but failed to start `kube-dns` using Addon Manager. Turned out his cluster was based on CentOS 7 and did not have PyYAML module installed (this module is needed by Addon Manager to parse out objects from yaml files). Addon manager's logging might not be good so it was not obviously showing what was wrong.

We may insure PyYAML module is installed for the master role to make sure `kube-dns` could be managed by the Addon Manager. Manually create `kube-dns` works but it is not desired.

@eparis @ingvagabund

**Comment by ingvagabund** [comment]
Looking into kubernetes-addons role, the PyYAML is installed (roles/kubernetes-addons/tasks/generic-install.yml):

```yaml
- name: Set pyyaml package name
  set_fact:
    pyyaml_name: python-yaml

- name: Overwrite pyyaml package name for non-Debian
  set_fact:
    pyyaml_name: PyYAML
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: Install PyYAML for non-debian
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ pyyaml_name }}"
    state: latest
```
