### ISSUE TITLE
[Nginx Ingress Controller] Setting DNS resolver through ConfigMap doesn't work

### ISSUE THREAD

**Issue by rutsky** [kubernetes/contrib#2193]
In order to workaround #2188 I tried to set custom DNS resolver as specified in [Customization docs](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md#allowed-parameters-in-configuration-config-map).

I created ConfigMap:

```
apiVersion: v1                                                                                                                                   
data:                                                                                                                                            
  resolver: "8.8.8.8"                                                                                                                            
kind: ConfigMap                                                                                                                                  
metadata:                                                                                                                                        
  name: nginx-load-balancer-conf
```

added `https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md#allowed-parameters-in-configuration-config-map` to list of `/nginx-ingress-controller`arguments (as specified [here](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/custom-configuration/rc-custom-configuration.yaml)).

And recreated `nginx-ingress-controller` replication controller.

Still pod contains incorrect resolver (and fails):

```
$ kubectl --kubeconfig admin.conf exec nginx-ingress-controller-s3lhg -- cat /etc/nginx/nginx.conf | grep resolver
    # Custom dns resolver.
    resolver 2001:4860:4860::8844 2001:4860:4860::8888 8.8.8.8 valid=30s;
```

I believe ConfigMap is properly applied in my configuration: when I add to ConfigMap other parameters, e.g. `body-size: 10m`, they are being properly applied --- I see changes in `/etc/nginx/nginx.conf`.
