### ISSUE TITLE
[Nginx Ingress Controller] Usage memory kept growing up until the memory limit.

### ISSUE THREAD

**Issue by Yancey1989** [kubernetes/contrib#2215]
The memory nginx ingress controller pod  usage memory kept growing up until the memory limit, and later it will reload automatic. Is this a bug?

**Comment by aledbf** [comment]
@Yancey1989 which limits are you specifying?

**Comment by Yancey1989** [comment]
@aledbf Here is a fragment of my yaml, I specify the the equal memory limit and request.
```
        resources:
          limits:
            cpu: "20"
            memory: "30Gi"
          requests:
            cpu: "12"
            memory: "30Gi"
```
