### ISSUE TITLE
Using Ingress for spark web-ui can't load the static files

### ISSUE THREAD

**Issue by archerbj** [kubernetes/contrib#2238]
```
kubernetes ： 1.2 
ingress-controller: gcr.io/google_containers/nginx-ingress-controller:0.8.3
spark: 2.0.0
```
ingress yaml 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spark-ingress
  namespace: default
spec:
  rules:
  - host: k8s.spark.com
    http:
      paths:
      - path: /ui
        backend:
          serviceName: spark-master-service
          servicePort: 8080
```

Hi , I was about to using ingress to expose my spark-web-ui from kubernetes at a specific hostname like `http://k8s.spark.com/ui`

previously using service to do so works just fine. 

when i switch to use ingress , it seems the ui tried to load the static files from the host i specified in ingress rules just like below 

![screenshot](https://cloud.githubusercontent.com/assets/14799336/21586061/ea517214-d106-11e6-8395-7b2b0499a4b3.png)

**Comment by archerbj** [comment]
Problem solved by add ingress rules to route the request for static files 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spark-ingress
  namespace: default
spec:
  rules:
  - host: k8s.spark.com
    http:
      paths:
      - path: /ui
        backend:
          serviceName: spark-master-service
          servicePort: 8080
      - path: /static
        backend:
          serviceName: spark-master-service
          servicePort: 8080
```
