### ISSUE TITLE
[nginx-ingress-controller] question: SSL on root domain and www.

### ISSUE THREAD

**Issue by qrpike** [kubernetes/contrib#2297]
So I have a SSL wildcard cert and I was wondering do I have to define the routes for both non www and www domains? Or is there a way to define multiple hosts.

eg: 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysite.com
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: mysite-tls
      hosts:
        - mysite.com
        - www.mysite.com
  rules:
    - host: mysite.com
      http:
        paths:
          - path: /
            backend:
              serviceName: mysite
              servicePort: 80
    - host: www.mysite.com
      http:
        paths:
          - path: /
            backend:
              serviceName: mysite
              servicePort: 80
```

Or is there a way to combine them? This is obviously a simple example but when you have many /routes it can get long and ugly.

Thanks,
