### ISSUE TITLE
nginx-ingress-controller rewrite-target and path regex bad behavior

### ISSUE THREAD

**Issue by bmarks-mylo** [kubernetes/contrib#2350]
I'm trying to use path based routing to create a reverse proxy with ingress.  It looks like my paths get turned into regular expressions and match more than I want them to.  I also get different behavior based on trailing slashes.

My ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ops
  name: ops-reverse-proxy
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ops.mydomain.com
      http:
        paths:
        - path: /coverage
          backend:
            serviceName: cov-dashboard-service
            servicePort: 3000
        - path: /purecloud
          backend:
            serviceName: purecloud-tools
            servicePort: 3000
        - path: /reconciler
          backend:
            serviceName: reconciler
            servicePort: 3000
```

Resulting Nginx config:
```
...
location ~* /purecloud {
            proxy_set_header Host                   $host;

            # Pass Real IP
            proxy_set_header X-Real-IP              $remote_addr;

            # Allow websocket connections
            proxy_set_header                        Upgrade           $http_upgrade;
            proxy_set_header                        Connection        $connection_upgrade;

            proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host       $host;
            proxy_set_header X-Forwarded-Port       $server_port;
            proxy_set_header X-Forwarded-Proto      $pass_access_scheme;

            # mitigate HTTPoxy Vulnerability
            # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
            proxy_set_header Proxy                  "";

            proxy_connect_timeout                   5s;
            proxy_send_timeout                      60s;
            proxy_read_timeout                      60s;

            proxy_redirect                          off;
            proxy_buffering                         off;

            proxy_http_version                      1.1;

        rewrite /purecloud/(.*) /$1 break;
        rewrite /purecloud / break;
        proxy_pass http://ops-purecloud-tools-3000;

        }
...
```

 I'm seeing:
ops.mydomain.com/purecloudrandomstring => gets routed to the purecloud service, I would expect this to result in a 404

ops.mydomain.com/purecloud/qstats => gets redirected to ops.mydomain.com/qstats/, I would expect no redirect and for my service to receive /qstats
ops.mydomain.com/purecloud/qstats/ => page opens, no issues 

ops.mydomain.com/purecloud => any root level resources in page don't load ie. style.css tries to load as ops.mydomain.com/style.css not .../purecloud/style.css

**Comment by bmarks-mylo** [comment]
I should also mention that I originally tried to achieve this behavior without using the rewrite annotation but I don't see a way to add a trailing slash to the proxy_pass value that is set in the nginx config.

**Comment by bartoszhernas** [comment]
I have the same issue, I am using rewrite to proxy pass my frontend app API's to not have to use CORS

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboardcors-lb
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: "/"
spec:
  tls:
  - secretName: dashboard-tls
    hosts:
    - web.whatsahoy.com
  rules:
  - host: web.whatsahoy.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: coreapi-service
          servicePort: 8000
      - path: /search
        backend:
          serviceName: search-service
          servicePort: 8000
```

it works fine until you try to use 
`web.whatsahoy.com/api/airports/search/` which is then passed to search-service and not coreapi-service :(
