### ISSUE TITLE
Nginx Ingress Controller throwing 502

### ISSUE THREAD

**Issue by craigwillis85** [kubernetes/contrib#2363]
Hi

I'm using the nginx ingress controller DaemonSet example to expose a service of mine.

I have an Ingress, which is below:

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: my-service
      namespace: default
    spec:
      rules:
      - host: mydomain.com
        http:
          paths:
          - path: /
            backend:
              serviceName: my-service
              servicePort: 80

The problem is, I keep seeing `502` errors when i hit certain pages of mydomain.com, the errors are similar to below:

    2017/02/02 13:44:36 [error] 159#159: *63 upstream prematurely closed connection while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /test.html HTTP/1.1", upstream: "http://10.123.45.11:80/test.html", host: "mydomain.com"

`10.123.45.11` is an IP of one of the pods running the `my-service` service.

I'm unsure as to why this happening as it shouldn't be throwing a `502`

Any ideas?

**Comment by naveensrinivasan** [comment]
@aledbf Any clues. This is also happening in non-DaemonSet? Thanks

**Comment by aledbf** [comment]
@naveensrinivasan what version are you using. Please update to 0.9-beta.8

**Comment by aledbf** [comment]
Also, the repository for ingress is https://github.com/kubernetes/ingress

**Comment by saravanakumar-periyasamy** [comment]
@aledbf - is there a specific fix in 0.9-beta.8 that address this 502 issue? We are also facing 502 issue and we are using 0.8.3 version.

**Comment by somejfn** [comment]
On 0.9.0-beta.12, this ingress will throw 502s on both host.   This is working just fine on 0.9.0-beta.3:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: matchbox
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - hosts:
        - matchbox1-rpc.somedomain.io
  rules:
    - host: matchbox1.somedomain.io
      http:
        paths:
          - path: /
            backend:
              serviceName: matchbox
              servicePort: 8080
    - host: matchbox1-rpc.somedomain.io
      http:
        paths:
          - path: /
            backend:
              serviceName: matchbox
              servicePort: 8081
```

Looking the logs,  it sounds like it tries to reach the clear text host over TLS:

10.2.8.0 - [10.2.8.0] - - [18/Oct/2017:15:25:35 +0000] "GET / HTTP/1.1" 502 173 "-" "curl/7.47.0" 101 0.001 [prd122-matchbox-8080] 10.2.6.14:8080 0 0.001 502
2017/10/18 15:25:35 [error] 2406#2406: *12572 SSL_do_handshake() failed (SSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol) while SSL handshaking to upstream, client: 10.2.5.0, server: matchbox1.somedomain.io, request: "GET / HTTP/1.1", upstream: "https://10.2.6.14:8080/", host: "matchbox1.somedomain.io"
