### ISSUE TITLE
[nginx] tls is not recognized

### ISSUE THREAD

**Issue by FaKod** [kubernetes/contrib#2482]
Hi,

following the example here https://github.com/kubernetes/ingress/tree/master/examples/tls-termination/nginx

Everything looks fine except curl shows:

```
$curl https://x.x.ch
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html
```
nginx.conf shows:
```
$ kubectl -n kube-system exec -it nginx-ingress-controller-557735307-mg5md -- cat /etc/nginx/nginx.conf | grep ssl_certificate
        ssl_certificate /etc/nginx-ssl/system-snake-oil-certificate.pem;
        ssl_certificate_key /etc/nginx-ssl/system-snake-oil-certificate.pem;
```

My Ingress is:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
  name: my_ingress
spec:
  tls:
    - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: dashboard
          servicePort: 8080
```

my_ingress is created as shown in the example.
It seems that a wrong cert is used.
(ingress nginx container version 0.8.3)

Any hint?
