### ISSUE TITLE
SSL redirect on nginx-ingress-controller not working

### ISSUE THREAD

**Issue by saiyen2002** [kubernetes/contrib#2487]
looking at doc here

https://github.com/kubernetes/ingress/tree/master/controllers/nginx#https

it says that by Default the controller redirects to HTTPS if TLS is enabled for that ingress

I have TLS defined in my ingress-controller, but HTTPS is not working, only HTTP. Trying HTTPS sends to default backend.

my ingress looks as follows
```
Name:                   cafe-ingress
Namespace:              default
Address:                192.168.20.232
Default backend:        default-http-backend:80 (<none>)
TLS:
  cafe-secret terminates cafe.example.com
Rules:
  Host                  Path    Backends
  ----                  ----    --------
  cafe.example.com
                        /tea            tea-svc:80 (<none>)
                        /coffee         coffee-svc:80 (<none>)
Annotations:
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason  Message
  ---------     --------        -----   ----                            -------------   --------        ------  -------
  34m           34m             1       {nginx-ingress-controller }                     Normal          CREATE  default/cafe-ingress
  34m           34m             1       {nginx-ingress-controller }                     Normal          UPDATE  default/cafe-ingress
  34m           34m             1       {nginx-ingress-controller }                     Normal          CREATE  ip: 192.168.20.232
```
In the actual nginx-ingress container looking at the nginx.conf i can see that Hosts and paths are only created in port 80 host.

```
 server {
        server_name cafe.example.com;
        listen 80;
```

the server block for 443 does not have the example

```
    server {
        server_name _;
        listen 80;
        listen 443  ssl spdy http2;
		
```

I deployed the nginx-ingress-controller with the image gcr.io/google_containers/nginx-ingress-controller:0.8.3 My deployment is as follows. 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: default
  labels:
    app: nginx-ingress-lb
    group: lb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ingress-lb
        name: nginx-ingress-lb
        group: lb
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-ingress-lb
        image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
        - containerPort: 18080 
        - containerPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=default/nginx-default-backend
        - --nginx-configmap=default/nginx-ingress-lb-cfg

```

I originally setup this up with the example from here https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example and everything worked as expected.
but changing the controller to gcr.io/google_containers/nginx-ingress-controller:0.8.3 is what caused the issue

I am using kubernetes version 1.5.3. The cluster is running locally, not on any cloud platform.
