### ISSUE TITLE
cluster-autoscaler: v0.5.0 don't send logs

### ISSUE THREAD

**Issue by mashayev** [kubernetes/contrib#2500]
Hi,

I've upgraded cluster-autoscaler from v0.4.0 to 0.5.0 and the created container not sending logs any more, the logs are empty.

From the documentation I didn't see any change from v0.4 to v0.5 regarding the logs.

```
      containers:
        - image: xplenty/kubernetes-autoscaler:v0.5.0
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --kubernetes=${MASTER_URL}
            - --v=4
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=true
            - --nodes=${ASG_MIN}:${ASG_MAX}:${ASG_NAME}
```
