### ISSUE TITLE
[keepalived-vip]: Error getting POD information (k8s v1.6.1)

### ISSUE THREAD

**Issue by discostur** [kubernetes/contrib#2520]
Hi,

just tried out keepalived-vip with the new kubernetes v1.6.1 and i'm getting the following error:

```
F0404 09:52:28.045035       1 controller.go:298] Error getting POD information: timed out waiting to observe own status as Running
goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0x1d9fd00, 0xc400000000, 0x83, 0xf2)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1d7f800, 0xc400000003, 0xc4203b9b00, 0x1d1a03f, 0xd, 0x12a, 0x0)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1d7f800, 0xc400000003, 0x150ae12, 0x21, 0xc42065bc88, 0x1, 0x1)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x150ae12, 0x21, 0xc42065bc88, 0x1, 0x1)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.newIPVSController(0xc4205a08a0, 0xc42001000e, 0x7, 0x12ffd00, 0x7fff6dde1720, 0x15, 0x3)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/controller.go:298 +0x10ee
main.main()
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/main.go:115 +0x29a
```

I think it may be related to the new RBAC feature introduced in v.1.6.1?

**Comment by aledbf** [comment]
@discostur similar issue to https://github.com/kubernetes/dashboard/issues/1800

**Comment by eugene-chow** [comment]
@discostur This is my RBAC config that solved this error. Create a ServiceAccount first with `kubectl create sa kube-keepalived-vip`.

@aledbf I would like to contribute the config below. Is there a specific folder where you like to put it? Also, I think keepalived needed a ClusterRoleBinding rather than a RoleBinding. Can you confirm that this is correct? Thanks!

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: kube-keepalived-vip
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - endpoints
  - services
  verbs: ["get", "list", "watch"]
```

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: kube-keepalived-vip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-keepalived-vip
subjects:
- kind: ServiceAccount
  name: kube-keepalived-vip
  namespace: default
```

**Comment by aledbf** [comment]
@eugene-chow please open a PR adding a RBAC section in the README.md inside the folder https://github.com/kubernetes/contrib/tree/master/keepalived-vip with the examples

**Comment by discostur** [comment]
@eugene-chow still getting the error:

```
F0405 14:29:37.046117       1 controller.go:298] Error getting POD information: timed out waiting to observe own status as Running
goroutine 1 [running]:
```

I even tried to bind it to the "cluster-admin" cluster role but can't get it working:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-keepalived-vip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin 
subjects:
- kind: ServiceAccount
  name: kube-keepalived-vip
  namespace: default
```

Still investigating ...

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by eugene-chow** [comment]
I missed out the assignment of the ServiceAccount to the DaemonSet.

Modify `vip-daemonset.yaml` to include the `serviceAccount` directive. It should look something like this:
```
spec:
  template:
    metadata:
      labels:
        name: kube-keepalived-vip
    spec:
      hostNetwork: true
      serviceAccount: kube-keepalived-vip
      containers:
        - image: gcr.io/google_containers/kube-keepalived-vip:0.9
```

Then reapply the YAML with
```
kubectl apply -f vip-daemonset.yaml
```

The pods should restart with the new config. If it didn't, delete the DaemonSet and recreate it. The error should go away.

**Comment by discostur** [comment]
@eugene-chow haha just found it out 1 minute before your post ;) Thanks anyway!!

**Comment by eugene-chow** [comment]
Mind-reading. I’m freaking out right now :D

**Comment by eugene-chow** [comment]
Fyi, I added `configmaps` to the ClusterRole. The lack of it prevented the cluster config from being generated.

This part won't show up In the pod logs if the `configmaps` permission is absent.
```
Activating healthchecker for service [10.2.34.2]:8080
Using LinkWatch kernel netlink reflector...
VRRP_Instance(vips) Entering BACKUP STATE
VRRP_Instance(vips) Transition to MASTER STATE
VRRP_Instance(vips) Entering MASTER STATE
VRRP_Instance(vips) using locally configured advertisement interval (1000 milli-sec)
```

**Comment by discostur** [comment]
Can confirm that loading configmap is now working! Here is my full rbac-config for 1.6.1:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-keepalived-vip
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - endpoints
  - services
  - configmaps
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-keepalived-vip 
  namespace: default 
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-keepalived-vip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-keepalived-vip
subjects:
- kind: ServiceAccount
  name: kube-keepalived-vip
  namespace: default
```

**Comment by genti-t** [comment]
still getting the error: 
```
F0502 16:14:11.556816       1 controller.go:298] Error getting POD information: timed out waiting to observe own status as Running
```

I'am using the full  rbac as @discostur described, 

my configMap:
```
 apiVersion: v1
kind: ConfigMap
metadata:
  name: vip-configmap
data:
  10.0.2.100: default/echoheaders
```

my ds:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-keepalived-vip
spec:
  template:
    metadata:
      labels:
        name: kube-keepalived-vip
    spec:
      hostNetwork: true
      serviceAccount: kube-keepalived-vip
      containers:
        - image: gcr.io/google_containers/kube-keepalived-vip:0.9
          name: kube-keepalived-vip
          # imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /dev
              name: dev
          # use downward API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          # to use unicast
          args:
          - --services-configmap=default/vip-configmap
          - --v=10
          # unicast uses the ip of the nodes instead of multicast
          # this is useful if running in cloud providers (like AWS)
          #- --use-unicast=true
      volumes:
        - name: modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
      nodeSelector:
        role: "vip"

```
I'm using kubernetes v1.6.2,
Any help would be much appreciated

**Comment by eugene-chow** [comment]
just to be sure that it's RBAC, can you run `kubectl edit clusterrole kube-keepalived-vip`. under `resources` add a new entry "*". if the error vanishes, keepalive may require extra permissions.

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-keepalived-vip
rules:
- apiGroups: [""]
  resources:
  - "*"
  - pods
  - nodes
  - endpoints
  - services
  - configmaps
  verbs: ["get", "list", "watch"]
```
