### ISSUE TITLE
[keepalived-vip] Doesn't detect hostNetwork pods & use of clusterIP VS podIP

### ISSUE THREAD

**Issue by eugene-chow** [kubernetes/contrib#2534]
@aledbf I tried pointing keepalived to a Service which points to an Ingress on `hostNetwork`. It failed to pick up the Ingress' `podIP`, which is equivalent to the `hostIP`. I haven't figured it out from the source code but I suspect it's on `hostNetwork`.

Here's the Service defn for the Ingress. I tested that `NodePort` in the original config wasn't necessary.
```
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
```

The keepalived ConfigMap for the Ingress.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: vip-configmap
data:
  172.16.32.15: kube-system/traefik
```

Also, is there a reason for pointing keepalived to the podIP instead of the Service's `clusterIP`? I think `clusterIP` would be a better choice because its IP more stable than the `podIP` and it's also load-balanced by iptables.

Thanks!
