### ISSUE TITLE
startup-script no longer seems to run on host for 1.6

### ISSUE THREAD

**Issue by tonglil** [kubernetes/contrib#2538]
It seems like this daemonset image no longer executes commands on the host w/ K8s 1.6.

https://github.com/kubernetes/contrib/tree/master/startup-script

I have a cluster w/ nodes running 1.6.0 and 1.5.2, and the same daemonset running.

On 1.6.0 (echo is written to /tmp/test inside the container):
```
bash-4.3# ls -la /tmp/
total 12
drwxrwxrwt    1 root     root          4096 Apr  7 21:05 .
drwxr-xr-x    1 root     root          4096 Apr  7 21:05 ..
-rw-r--r--    1 root     root            12 Apr  7 21:05 test
-rw-r--r--    1 root     root             0 Apr  7 21:05 startup-script-v1
```

On 1.5.2 (expected since the commands are executed on the host node):
```
bash-4.3# ls -la /tmp
total 8
drwxrwxrwt    2 root     root          4096 Oct 18 18:58 .
drwxr-xr-x    1 root     root          4096 Apr  7 21:05 ..
```

```yaml
---
kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: test-ds

spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  minReadySeconds: 30

  template:
    metadata:
      labels:
        app: test-ds

    spec:
      hostPID: true
      containers:
        - name: test-ds
          image: gcr.io/google-containers/startup-script:v1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 50m
          securityContext:
            privileged: true
          env:
          # Increment this value to make new DS script apply
          - name: CHECKPOINT_PATH
            value: /tmp/startup-script-v1
          - name: STARTUP_SCRIPT
            value: |
              #!/bin/bash

              set -o nounset
              set -o errexit
              set -o pipefail

              echo "Start"

              echo "hello world" > /tmp/test

              echo "End"
```
