### ISSUE TITLE
nginx ingress controller does not handle host headers longer than 47 characters

### ISSUE THREAD

**Issue by codecap** [kubernetes/contrib#2573]
__Version__: 0.8.3

__Working__:  Host with 46 characters
```yaml
  - host: kubernetes-dashboard2345678901234567890123456
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 9090
```

curl -k -D- -L -H "Host: kubernetes-dashboard2345678901234567890123456"  [IP]
```bash
HTTP/1.1 401 Unauthorized
Server: nginx/1.11.3
Date: Tue, 02 May 2017 11:26:52 GMT
Content-Type: text/html
Content-Length: 195
Connection: keep-alive
WWW-Authenticate: Basic realm="Authentication Required"

<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.11.3</center>
</body>
</html>
```

__Broken__: Host with 50 characters
```yaml
  - host: kubernetes-dashboard23456789012345678901234567890
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 9090
```
curl -k -D- -L -H "Host: kubernetes-dashboard23456789012345678901234567890" [IP]
```bash
HTTP/1.1 404 Not Found
Server: nginx/1.11.3
Date: Tue, 02 May 2017 11:27:06 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains; preload

default backend - 404
```
