### ISSUE TITLE
ingress.kubernetes.io/affinity: "cookie" is not working

### ISSUE THREAD

**Issue by RTBathula** [kubernetes/contrib#2631]
Hi,
I followed this tutorial https://github.com/kubernetes/ingress/tree/master/examples/affinity/cookie/nginx
And yes I have created and running one backend(one pod and service). Then I have added one ingress type
and mentioned like this 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress
  annotations:     
    kubernetes.io/ingress.class: "gce"  
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: red //My service name 
          servicePort: 80
```

But as i am doing curl, I am not seeing cookie is set in headers.
