### ISSUE TITLE
[keepalived-vip] Traffic is not forwarded to service when pod not running on MASTER

### ISSUE THREAD

**Issue by carlosedp** [kubernetes/contrib#2637]
I have a fresh deployment of K8s 1.6.3 using Weave net on 1 master and 2 minions. I've set a Traefik ingress controller using a deployment with 2 replicas. The replicas are currently running on both minions.

Then I deployed keepalived-vip and it started a pod on each of my 3 nodes (master+minions). 

The problem is that when I'm on the master node, I can `curl` any of the three IP addresses and get a http response but when I'm on any other machine in the same network, I can't `curl` the VIP. The only ones that answer are the two nodes that have traefik controller listening on port 80.

I checked around and this only occurs when the keepalived MASTER is the master node which don't have the controller pod running (also there's nothing listening on port 80) but when I killed the keepalived processes in my master forcing one of the nodes to assume the VIP, `curl` started working perfectly on any machine.

###Endpoints

```
NAMESPACE     NAME                         ENDPOINTS                               AGE
default       kubernetes                   10.178.11.236:6443                      4h
kube-system   heapster                     10.46.0.2:8082                          4h
kube-system   kube-controller-manager      <none>                                  4h
kube-system   kube-dns                     10.32.0.2:53,10.32.0.2:53               4h
kube-system   kube-scheduler               <none>                                  4h
kube-system   kubernetes-dashboard         10.46.0.1:9090                          4h
kube-system   monitoring-influxdb          10.46.0.3:8086                          4h
kube-system   tiller-deploy                10.46.0.4:44134                         4h
kube-system   traefik-ingress-controller   10.178.11.237:80,10.178.11.238:80       4h
kube-system   traefik-web-ui               10.178.11.237:8081,10.178.11.238:8081   4h
```

### Services
```
NAMESPACE     NAME                         CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
default       kubernetes                   10.96.0.1        <none>        443/TCP         4h
kube-system   heapster                     10.98.175.4      <none>        80/TCP          4h
kube-system   kube-dns                     10.96.0.10       <none>        53/UDP,53/TCP   4h
kube-system   kubernetes-dashboard         10.107.153.235   <none>        80/TCP          4h
kube-system   monitoring-influxdb          10.105.161.7     <none>        8086/TCP        4h
kube-system   tiller-deploy                10.102.54.84     <none>        44134/TCP       4h
kube-system   traefik-ingress-controller   10.110.69.223    <nodes>       80:30080/TCP    4h
kube-system   traefik-web-ui               10.97.196.245    <none>        8081/TCP        4h
```

###Logs from Master node

```
[root@master-1 ~]# kdesc keepal 1
Pod: kube-keepalived-vip-c6fv0

Name:           kube-keepalived-vip-c6fv0
Namespace:      default
Node:           master-1/10.178.11.236
Start Time:     Wed, 14 Jun 2017 14:11:40 +0000
Labels:         name=kube-keepalived-vip
                pod-template-generation=1
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"DaemonSet","namespace":"default","name":"kube-keepalived-vip","uid":"62e9a9c6-510b-11e7-9be9-fa163e5e86fb"...
Status:         Running
IP:             10.178.11.236
Controllers:    DaemonSet/kube-keepalived-vip
Containers:
  kube-keepalived-vip:
    Container ID:       docker://1b09cfc8e4d5a71b7f938bdca9cca905d894e78e06ee3672b3fcf8aef6ccf15b
    Image:              aledbf/kube-keepalived-vip:0.14
    Image ID:           docker-pullable://docker.io/aledbf/kube-keepalived-vip@sha256:7e451b871a13e931402f91586f96b267a7a8eaa8f7c27a46eb5e82237a029cf8
    Port:
    Args:
      --services-configmap=default/vip-configmap
    State:              Running
      Started:          Wed, 14 Jun 2017 14:12:08 +0000
    Last State:         Terminated
      Reason:           Error
      Exit Code:        255
      Started:          Mon, 01 Jan 0001 00:00:00 +0000
      Finished:         Wed, 14 Jun 2017 14:11:51 +0000
    Ready:              True
    Restart Count:      2
    Environment:
      POD_NAME:         kube-keepalived-vip-c6fv0 (v1:metadata.name)
      POD_NAMESPACE:    default (v1:metadata.namespace)
    Mounts:
      /dev from dev (rw)
      /lib/modules from modules (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-keepalived-vip-token-n9tdh (ro)
Conditions:
  Type          Status
  Initialized   True
  Ready         True
  PodScheduled  True
Volumes:
  modules:
    Type:       HostPath (bare host directory volume)
    Path:       /lib/modules
  dev:
    Type:       HostPath (bare host directory volume)
    Path:       /dev
  kube-keepalived-vip-token-n9tdh:
    Type:       Secret (a volume populated by a Secret)
    SecretName: kube-keepalived-vip-token-n9tdh
    Optional:   false
QoS Class:      BestEffort
Node-Selectors: <none>
Tolerations:    node.alpha.kubernetes.io/notReady=:Exists:NoExecute
                node.alpha.kubernetes.io/unreachable=:Exists:NoExecute
Events:         <none> 


Pod Logs:

Starting Keepalived v1.3.5 (unknown)
Unable to resolve default script username 'keepalived_script' - ignoring
Opening file '/etc/keepalived/keepalived.conf'.
Starting Healthcheck child process, pid=17
Starting VRRP child process, pid=18
Initializing ipvs
Opening file '/etc/keepalived/keepalived.conf'.
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
Using LinkWatch kernel netlink reflector...
I0614 14:12:08.951919       1 keepalived.go:159] reloading keepalived
Opening file '/etc/keepalived/keepalived.conf'.
Got SIGHUP, reloading checker configuration
Initializing ipvs
Opening file '/etc/keepalived/keepalived.conf'.
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
Activating healthchecker for service [10.178.11.241]:80
Activating healthchecker for service [10.178.11.241]:80
Using LinkWatch kernel netlink reflector...
VRRP_Instance(vips) Entering BACKUP STATE
VRRP_Instance(vips) Transition to MASTER STATE
VRRP_Instance(vips) Entering MASTER STATE
VRRP_Instance(vips) using locally configured advertisement interval (1000 milli-sec) 


[root@master-1 ~]#  kubectl exec kube-keepalived-vip-c6fv0 cat /etc/keepalived/keepalived.conf

global_defs {
  vrrp_version 3
  vrrp_iptables KUBE-KEEPALIVED-VIP
}

vrrp_script chk_haproxy {
  script "/haproxy-check.sh"
  interval 1
}

vrrp_instance vips {
  state BACKUP
  interface eth0
  virtual_router_id 50
  priority 100
  nopreempt
  advert_int 1

  track_interface {
    eth0
  }
  virtual_ipaddress {
    10.178.11.241
  }
}

# Service: kube-system-traefik-ingress-controller
virtual_server 10.178.11.241 80 {
  delay_loop 5
  lvs_sched wlc
  lvs_method NAT
  persistence_timeout 1800
  protocol TCP

  real_server 10.178.11.237 80 {
    weight 1
    TCP_CHECK {
      connect_port 80
      connect_timeout 3
    }
  }

  real_server 10.178.11.238 80 {
    weight 1
    TCP_CHECK {
      connect_port 80
      connect_timeout 3
    }
  }
} 


[root@master-1 ~]# netstat -anpl |grep 80
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      4677/etcd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      800/sshd
tcp        0      0 127.0.0.1:40680         127.0.0.1:2379          ESTABLISHED 5387/kube-apiserver
tcp        0      0 127.0.0.1:40180         127.0.0.1:2379          ESTABLISHED 4677/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:40680         ESTABLISHED 4677/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:40180         ESTABLISHED 4677/etcd
tcp6       0      0 :::22                   :::*                    LISTEN      800/sshd
tcp6       0      0 :::30080                :::*                    LISTEN      6171/kube-proxy
raw        0      0 0.0.0.0:112             0.0.0.0:*               7           13380/keepalived
raw        0      0 0.0.0.0:112             0.0.0.0:*               7           13380/keepalived
unix  2      [ ACC ]     STREAM     LISTENING     35880    5141/kubelet         /var/run/dockershim.sock
unix  2      [ ]         DGRAM                    7804     1/systemd            /run/systemd/notify
unix  2      [ ]         DGRAM                    7806     1/systemd            /run/systemd/cgroups-agent
unix  3      [ ]         STREAM     CONNECTED     14803    514/dbus-daemon      /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     14802    505/polkitd
unix  3      [ ]         STREAM     CONNECTED     34803    5141/kubelet
unix  2      [ ]         DGRAM                    14805    505/polkitd
unix  3      [ ]         STREAM     CONNECTED     14680    509/systemd-logind    


[root@master-1 ~]# ps aux|grep keepalived
root      4203  0.0  0.0 112648   964 pts/0    S+   18:32   0:00 grep --color=auto keepalived
root     13347  0.1  0.4  36332 17568 ?        Ssl  14:12   0:18 /kube-keepalived-vip --services-configmap=default/vip-configmap
root     13378  0.0  0.0  69372  3032 ?        S    14:12   0:00 keepalived --dont-fork --log-console --release-vips --pid /keepalived.pid
root     13379  0.0  0.0  71568  2584 ?        S    14:12   0:01 keepalived --dont-fork --log-console --release-vips --pid /keepalived.pid
root     13380  0.0  0.0  75944  2316 ?        S    14:12   0:01 keepalived --dont-fork --log-console --release-vips --pid /keepalived.pid
[root@master-1 ~]# kill -9 13347 13378 13379 13380 

```

### The Minion assumed VIP master

```
[root@master-1 ~]# klog keepali 3
Pod: kube-keepalived-vip-t579n

I0614 14:12:58.361202       1 main.go:197] Creating API server client for https://10.96.0.1:443
I0614 14:12:58.371511       1 keepalived.go:186] cleaning ipvs configuration
I0614 14:12:58.534971       1 main.go:121] starting LVS configuration
I0614 14:12:58.600283       1 utils.go:150] network interfaces: [{Index:2 MTU:1500 Name:eth0 HardwareAddr:fa:16:3e:77:46:55 Flags:up|broadcast|multicast} {Index:4 MTU:1376 Name:datapath HardwareAddr:6a:b4:db:11:74:81 Flags:up|broadcast|multicast} {Index:6 MTU:1376 Name:weave HardwareAddr:ca:28:03:56:24:c2 Flags:up|broadcast|multicast} {Index:7 MTU:1500 Name:dummy0 HardwareAddr:0a:c9:e4:8a:35:4c Flags:broadcast} {Index:11 MTU:65470 Name:vxlan-6784 HardwareAddr:aa:69:66:e9:9f:48 Flags:up|broadcast|multicast}]
I0614 14:12:58.604461       1 main.go:131] starting keepalived to announce VIPs
Starting Keepalived v1.3.5 (unknown)
Unable to resolve default script username 'keepalived_script' - ignoring
Opening file '/etc/keepalived/keepalived.conf'.
Starting Healthcheck child process, pid=18
Initializing ipvs
Starting VRRP child process, pid=19
Opening file '/etc/keepalived/keepalived.conf'.
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
Using LinkWatch kernel netlink reflector...
I0614 14:12:58.709928       1 keepalived.go:159] reloading keepalived
Opening file '/etc/keepalived/keepalived.conf'.
Got SIGHUP, reloading checker configuration
Initializing ipvs
Opening file '/etc/keepalived/keepalived.conf'.
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
Using LinkWatch kernel netlink reflector...
VRRP_Instance(vips) Entering BACKUP STATE
Activating healthchecker for service [10.178.11.241]:80
Activating healthchecker for service [10.178.11.241]:80
VRRP_Instance(vips) Transition to MASTER STATE
VRRP_Instance(vips) Entering MASTER STATE
VRRP_Instance(vips) using locally configured advertisement interval (1000 milli-sec) 
```

**Comment by carlosedp** [comment]
I also reset the environment and tested with Flannel network and the same problem occurs.

**Comment by carlosedp** [comment]
Found the problem, I had my Traefik delpoyment with HostNetwork: true and hostPort configured. This messed up with the routing and the traffic never hit the nodes.

Used the deployment and services below:

```
[root@master-1 tmp]# cat rbac.yaml
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
[root@master-1 tmp]# cat dep.yaml
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --logLevel=ERROR

[root@master-1 tmp]# cat svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80

[root@master-1 tmp]# cat traefik-ui.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - port: 8080
    name: admin
    protocol: TCP
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  rules:
  - host: traefik.kube.com
    http:
      paths:
      -  backend:
          serviceName: traefik-web-ui
          servicePort: admin
---
```
