### ISSUE TITLE
[keepalived-vip] Can not use service in another Namespace

### ISSUE THREAD

**Issue by f0** [kubernetes/contrib#2657]
Hi,

I followed the Readme (with RBAC) and  tested the default manifests (keepalived and echoheaders in the default namespace), it does work.

If i try to use a Service (echoheaders) in another Namespace , keepalived complains that no VIP is avaible and the pod's are crashing.

My Cluster is 1.6.2 with RBAC 

any Ideas? How can i Debug this ? 

My configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: vip-configmap
data:
  10.62.3.168: testecho/echoheaders
```

regards f0

**Comment by zjj2wry** [comment]
may you need set ```watch-all-namespaces``` true

**Comment by cornelius-keller** [comment]
yes that is correct. I had the same issue. Passing `--watch-all-namespaces` as an argument to the pod solves the issue. This shoud be documented.
my daemonset now looks like this: 
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-keepalived-vip
spec:
  template:
    metadata:
      labels:
        name: kube-keepalived-vip
    spec:
      hostNetwork: true
      serviceAccount: kube-keepalived-vip
      containers:
        - image: gcr.io/google_containers/kube-keepalived-vip:0.11
          name: kube-keepalived-vip
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /dev
              name: dev
          # use downward API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          # to use unicast
          args:
          - --services-configmap=default/vip-configmap
          - --v=6
          - --watch-all-namespaces
          # unicast uses the ip of the nodes instead of multicast
          # this is useful if running in cloud providers (like AWS)
          #- --use-unicast=true
          # vrrp version can be set to 2.  Default 3.
          #- --vrrp-version=2
      volumes:
        - name: modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
      nodeSelector:
        type: worker
```
