### ISSUE TITLE
ingress/controllers/nginx/examples/tls: wrong ingress.yaml

### ISSUE THREAD

**Issue by ensonic** [kubernetes/contrib#2668]
In the section "Finally create a tls Ingress rule:", the ingress.yaml should be simplified:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo
spec:
  tls:
  - secretName: foo-secret
  rules:
  - host: foo.bar.com
  backend:
    serviceName: echoheaders-x
    servicePort: 80
```

* the namespace does not need to be set
* there is no need to specify the host for spec.tls
* there is no need for the http part under spec.rules.host, even worse this way one won't have a default backend
