### ISSUE TITLE
Exechealthz pod though an error "nslookup: can't resolve 'kubernetes.default.svc.cluster.local': Name does not resolve" for ARCH=s390x

### ISSUE THREAD

**Issue by guirish** [kubernetes/contrib#2687]
Hi,

I have setup a local cluster using local-up-cluster.sh to verify DNS functionality on s390x ARCH. 
I am observing a issue in the exechealthz pod, when I try to use it along with kube-dns and kube-dnsmasq pods and do a nslookup from an s390x/busybox pod. My DNS functionality is working as expected but I am observing errors in exechealthz container, with similar setup I do not observe any errors in exechealthz container on intel.

Any pointer on this will be very helpful.

Updating YML (dns-addon.yml) used to deploy the pods.
```
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.0.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP


---


apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v20
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v20
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v20
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v20
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: kubedns
        image: gcr.io/google_containers/k8s-dns-kube-dns-s390x:1.14.1
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        livenessProbe:
          httpGet:
            path: /healthz-kubedns
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 5
        args:
        - --domain=cluster.local.
        - --dns-port=10053
        ports:
        - containerPort: 10053
          name: dns-local
          protocol: UDP
        - containerPort: 10053
          name: dns-tcp-local
          protocol: TCP
      - name: dnsmasq
        image: gcr.io/google_containers/k8s-dns-dnsmasq-s390x:1.14.1
        livenessProbe:
          httpGet:
            path: /healthz-dnsmasq
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - --cache-size=1000
        - --no-resolv
        - --server=127.0.0.1#10053
        - --log-facility=-
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      - name: healthz
        image: gcr.io/google_containers/exechealthz-s390x:1.2
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        args:
        - --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
        - --url=/healthz-dnsmasq
        - --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
        - --url=/healthz-kubedns
        - --port=8080
        - --quiet
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: Default
```
	  
Updating below all 3 pods (kube-dns,kube-dnsmasq and exechealthz) status
```
[root@XXXX kube]# kubectl get all --all-namespaces
NAMESPACE     NAME                    READY     STATUS    RESTARTS   AGE
kube-system   po/kube-dns-v20-kjmqj   3/3       Running   0          1h

NAMESPACE     NAME              DESIRED   CURRENT   READY     AGE
kube-system   rc/kube-dns-v20   1         1         1         1h

NAMESPACE     NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
default       svc/kubernetes   10.0.0.1     <none>        443/TCP         1h
kube-system   svc/kube-dns     10.0.0.10    <none>        53/UDP,53/TCP   1h
```

Updating below logs from exhealthz container:
```
[root@XXXX kube]# docker logs 4dd0807c5239
2017/07/20 09:08:28 Healthz probe on /healthz-dnsmasq error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local': Name does not resolve
, at 2017-07-20 09:08:26.72946 +0000 UTC, error exit status 1
2017/07/20 09:10:48 Healthz probe on /healthz-dnsmasq error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local': Name does not resolve
2017/07/20 09:52:38 Healthz probe on /healthz-kubedns error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local': Name does not resolve
, at 2017-07-20 09:52:36.734491 +0000 UTC, error exit status 1
2017/07/20 09:53:18 Healthz probe on /healthz-kubedns error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local': Name does not resolve
, at 2017-07-20 09:53:16.744527 +0000 UTC, error exit status 1
```

Describing below all pods logs:
```
[root@XXXX kube]# kubectl --namespace=kube-system describe pods
Name:           kube-dns-v19-bcz5t
Namespace:      kube-system
Node:           127.0.0.1/127.0.0.1
Start Time:     Wed, 19 Jul 2017 09:02:45 -0400
Labels:         k8s-app=kube-dns
                kubernetes.io/cluster-service=true
                version=v19
Status:         Running
IP:             172.17.0.2
Controllers:    ReplicationController/kube-dns-v19
Containers:
  kubedns:
    Container ID:       docker://fb936513b932d971514cc17d92cf5b178fd2f7bf1d30ba66a03a15128056d055
    Image:              gcr.io/google_containers/k8s-dns-kube-dns-s390x:1.14.1
    Image ID:           docker-pullable://gcr.io/google_containers/k8s-dns-kube-dns-s390x@sha256:b512b66d5fd9a3ce32f9aaa5e29a3672978d49e66b06f575d9bd0d6adce24594
    Ports:              10053/UDP, 10053/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
      --v=10
    Limits:
      cpu:      100m
      memory:   170Mi
    Requests:
      cpu:              100m
      memory:           70Mi
    State:              Running
      Started:          Wed, 19 Jul 2017 09:03:25 -0400
    Ready:              True
    Restart Count:      0
    Liveness:           http-get http://:8080/healthz delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:          http-get http://:8081/readiness delay=30s timeout=5s period=10s #success=1 #failure=4
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zmrn (ro)
    Environment Variables:      <none>
  dnsmasq:
    Container ID:       docker://2b6e676ea114ad6d5c3e9b725446c4056828ac367c227827dbd5cbd0c892e208
    Image:              gcr.io/google_containers/k8s-dns-dnsmasq-s390x:1.14.1
    Image ID:           docker-pullable://gcr.io/google_containers/k8s-dns-dnsmasq-s390x@sha256:1eb57c914d85af5a77a9af9632ad144106b3e12f68a8e8a734c5657c917753fd
    Ports:              53/UDP, 53/TCP
    Args:
      --cache-size=1000
      --no-resolv
      --server=127.0.0.1#10053
    State:              Running
      Started:          Wed, 19 Jul 2017 09:03:06 -0400
    Ready:              True
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zmrn (ro)
    Environment Variables:      <none>
  healthz:
    Container ID:       docker://66881707f667d565942700a74e9be210fdd513c74127d1060010d4f22ba8fb1d
    Image:              gcr.io/google_containers/exechealthz-s390x:1.2
    Image ID:           docker://sha256:975b7c9bebc616358d0e9cdd60dc59f7579731eb8f48361ca62547e532e8e9db
    Port:               8080/TCP
    Args:
      -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null && nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
      -port=8080
      -quiet
    Limits:
      cpu:      10m
      memory:   50Mi
    Requests:
      cpu:              10m
      memory:           50Mi
    State:              Running
      Started:          Wed, 19 Jul 2017 09:03:17 -0400
    Ready:              True
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zmrn (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         True
  PodScheduled  True
Volumes:
  default-token-9zmrn:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-9zmrn
QoS Class:      Burstable
Tolerations:    CriticalAddonsOnly=:Exists
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                    -------------                   --------        ------          -------
  2m            2m              1       {default-scheduler }                                    Normal          Scheduled       Successfully assigned kube-dns-v19-bcz5t to 127.0.0.1
  2m            2m              1       {kubelet 127.0.0.1}     spec.containers{dnsmasq}        Normal          Pulled          Container image "gcr.io/google_containers/k8s-dns-dnsmasq-s390x:1.14.1" already present on machine
  1m            1m              1       {kubelet 127.0.0.1}     spec.containers{dnsmasq}        Normal          Created         Created container with docker id 2b6e676ea114; Security:[seccomp=unconfined]
  1m            1m              1       {kubelet 127.0.0.1}     spec.containers{dnsmasq}        Normal          Started         Started container with docker id 2b6e676ea114
  1m            1m              1       {kubelet 127.0.0.1}     spec.containers{healthz}        Normal          Pulled          Container image "gcr.io/google_containers/exechealthz-s390x:1.2" already present on machine
  1m            1m              1       {kubelet 127.0.0.1}     spec.containers{healthz}        Normal          Created         Created container with docker id 66881707f667; Security:[seccomp=unconfined]
  1m            1m              1       {kubelet 127.0.0.1}     spec.containers{healthz}        Normal          Started         Started container with docker id 66881707f667
  1m            1m              1       {kubelet 127.0.0.1}     spec.containers{kubedns}        Normal          Pulled          Container image "gcr.io/google_containers/k8s-dns-kube-dns-s390x:1.14.1" already present on machine
  1m            1m              1       {kubelet 127.0.0.1}     spec.containers{kubedns}        Normal          Created         Created container with docker id fb936513b932; Security:[seccomp=unconfined]
  1m            1m              1       {kubelet 127.0.0.1}     spec.containers{kubedns}        Normal          Started         Started container with docker id fb936513b932
  27s           7s              3       {kubelet 127.0.0.1}     spec.containers{kubedns}        Warning         Unhealthy       Liveness probe failed: Get http://172.17.0.2:8080/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
