### ISSUE TITLE
Running deploy-local-cluster.sh failing - not picking up correct ansible_architecture

### ISSUE THREAD

**Issue by mjbright** [kubernetes/contrib#2699]
When running the deploy-etcd.yml playbook referenced by deploy-local-cluster.sh this fails with the error below.

It seems that the ansible_architecture is being incorrectly set (or rather not changed to amd64).

Running on ""Ubuntu 16.04.3 LTS"

TASK [etcd : Download tar file] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/.ansible/files", "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "https://github.com/coreos/etcd/releases/download/v2.2.3/etcd-v2.2.3-linux-x86_64.tar.gz"}

**Comment by brettdh** [comment]
No surprise, but this happens with `./deploy-cluster.sh` as well. (Remote host is Ubuntu 14.04.2)

**Comment by brettdh** [comment]
Temporary workaround for any other ansible neophytes like me reading this: added this to `ansible/roles/etcd/tasks/override_facts.yml`
```
# work around bug: https://github.com/kubernetes/contrib/issues/2699
- name: Override ansible_archecture
  set_fact:
    ansible_architecture: "amd64"
```
