### ISSUE TITLE
keepalived-vip / cyclic restart

### ISSUE THREAD

**Issue by beatlejuse** [kubernetes/contrib#2798]
I have this problem: https://youtu.be/gj8x2_D_G-k
after some time (a few days) working fine, cluster IP started to work intermittently.
this is evident in unstable pings.
in the logs the nodes and the logs of the containers kube-keepalived-vip seen that happen continually re-election of the master. however, it is not migrated to another node, but the cluster IP to the moment it becomes inaccessible.
redeploy does not change the situation.
Configmap is:
```
             apiVersion: v1
              kind: ConfigMap
              metadata:
                name: vip-configmap
                namespace: vip-system
              data:
                10.1.29.10: default/kubernetes
```
