### ISSUE TITLE
Automate perfdash configuration

### ISSUE THREAD

**Issue by porridge** [kubernetes/contrib#2812]
In https://github.com/kubernetes/contrib/pull/2796#pullrequestreview-76062138 @shyamjvs suggested that having names of sig-scalability CI jobs hard-coded in `perfdash/config.go` doesn't seem too clean.

If we could add some additional metadata to https://github.com/kubernetes/test-infra/blob/master/jobs/config.json then perf-dash could just periodically fetch the configuration from that file (via raw.githubusercontent.com)

What do @kubernetes/sig-testing-misc folks think about adding a `perfDashName` attribute (or something like it) to selected entries in `jobs.config`, and making perf-dash depend on that file?

**Comment by porridge** [comment]
@kubernetes/sig-scalability-feature-requests

**Comment by BenTheElder** [comment]
In the nearish future config.json is planned to go away. We [have plans](https://docs.google.com/document/d/1-ApXgeMOv6m79c3R1cLi3_t_xN5XANE_7vwtB0yFHmM/edit?usp=drivesdk) to move the functionality related to it out of the job images / bootstrap.py and to make Prow/config.yaml less redundant in Q1. Then we will roll up jobs/config.json into prow/config.yaml so jobs are configured in one place instead of a half dozen (with Jenkins).

@krzyzaxy @cjwagner and I will be working on these.

**Comment by krzyzacy** [comment]
it can probably be a prow config tag already, which is unlikely to change

**Comment by porridge** [comment]
@krzyzacy @BenTheElder @cjwagner so would you have anything against something like the following in `prow/config.yaml`?
```
[...]
periodics:
[...]
- cron: '1 8 * * 1,3,5' # Run at 00:01PST (8:01 UTC) on odd days (except sunday)
  agent: kubernetes
  name: ci-kubernetes-e2e-gce-scale-performance
  perfDash:
    # needs to be unique
    prefix: gce-5kNodes-master
  spec:
    containers:
    - args:
      - --timeout=1320
[...]
```

**Comment by krzyzacy** [comment]
@porridge you probably could use generic tags like

```
periodics:
[...]
- cron: '1 8 * * 1,3,5' # Run at 00:01PST (8:01 UTC) on odd days (except sunday)
  tags:
  - perfDash: gce-5kNodes-master
```

I don't think the `perfDash` field should be part of the prow periodic struct

**Comment by porridge** [comment]
@krzyzacy I can see one potential problem with the above. The way `tags` is used currently in that file is:
```
- tags:
  - generated   # AUTO-GENERATED by experiment/generate_tests.py - DO NOT EDIT!
  interval: 1h
  agent: kubernetes
[...]
```

This means that (at least in Python) the value of `tags` is a list of strings containing one element ("generated").

With your example above, value of `tags` will be a list of dictionaries (probably maps in Go?).

Will whatever parses this file tolerate such difference?
