### ISSUE TITLE
[Keepalived VIP] keepalived keeps restarting

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/contrib#2815]
I have follow the example to set up keepalived-vip daemonset. But got following error

```
VRRP child process(6794) died: Respawning
Starting VRRP child process, pid=6796
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
pid 6796 exited due to segmentation fault (SIGSEGV).
  Please report a bug at https://github.com/acassen/keepalived/issues
  and include this log from when keepalived started, what happened
  immediately before the crash, and your configuration file.
VRRP child process(6796) died: Respawning
Starting VRRP child process, pid=6798
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
pid 6798 exited due to segmentation fault (SIGSEGV).
  Please report a bug at https://github.com/acassen/keepalived/issues
  and include this log from when keepalived started, what happened
  immediately before the crash, and your configuration file.
VRRP child process(6798) died: Respawning
Starting VRRP child process, pid=6800
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
pid 6800 exited due to segmentation fault (SIGSEGV).
  Please report a bug at https://github.com/acassen/keepalived/issues
  and include this log from when keepalived started, what happened
  immediately before the crash, and your configuration file.
VRRP child process(6800) died: Respawning
```

This is the vip configmap,

```
# kubectl --namespace=kube-system get configmap vip-configmap -o yaml
apiVersion: v1
data:
  192.168.38.3: demo/nginx
  192.168.38.4: demo/tomcat
  192.168.38.5: demo/httpd
kind: ConfigMap
metadata:
  annotations:
    k8s.co/cloud-provider-config: '{"services":[{"uid":"d2cce28b-e5fd-11e7-889e-005056adb12a","ip":"192.168.38.1"},{"uid":"bb01f0ca-e610-11e7-889e-005056adb12a","ip":"192.168.38.2"},{"uid":"7c748d66-e632-11e7-889e-005056adb12a","ip":"192.168.38.3"},{"uid":"436b64ee-e9ea-11e7-889e-005056adb12a","ip":"192.168.38.4"},{"uid":"e6b45cf8-ea42-11e7-889e-005056adb12a","ip":"192.168.38.5"}]}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{},"name":"vip-configmap","namespace":"kube-system"}}
  creationTimestamp: 2017-12-21T03:16:33Z
  name: vip-configmap
  namespace: kube-system
  resourceVersion: "1059007"
  selfLink: /api/v1/namespaces/kube-system/configmaps/vip-configmap
  uid: 5898e43e-e5fd-11e7-8187-005056adb12a
```

And keepalived-vip daemonset,

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: kube-keepalived-vip
  name: kube-keepalived-vip
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: kube-keepalived-vip
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-keepalived-vip
    spec:
      containers:
      - args:
        - --services-configmap=kube-system/vip-configmap
        - --watch-all-namespaces=true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gcr.io/google_containers/kube-keepalived-vip:0.9
        imagePullPolicy: IfNotPresent
        name: kube-keepalived-vip
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /dev
          name: dev
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: modules
      - hostPath:
          path: /dev
          type: ""
        name: dev
  templateGeneration: 2
  updateStrategy:
    type: OnDelete
```
