### ISSUE TITLE
SSL passthrough

### ISSUE THREAD

**Issue by deathcoder** [kubernetes/contrib#2817]
Hi,
I'm trying to setup secure docker registry inside a kubernetes cluster with self-signed certificates, and im trying to test it on minikube
my end goal is to be able to do a `docker push  kube-registry.com/hello-world`
this is my setup, the registry:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v0
# A minikube issue prevents the following from working
#    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry
    version: v0
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v0
# A minikube issue prevents the following from working
#        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /cert/ca.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /key/domain.key
        - name: REGISTRY_LOG_LEVEL
          value: debug
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        - name: registry-cert 
          mountPath: /cert/
          readOnly: true
        - name: registry-key 
          mountPath: /key/
          readOnly: true
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: kube-registry-volume
      - name: registry-cert
        secret:
          secretName: registry-cert
      - name: registry-key
        secret:
          secretName: registry-key

```

and the service:
```
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry
  ports:
  - name: registry
    port: 5000
    nodePort: 31000
    protocol: TCP
  type: NodePort

```

i also generated the self-signed certificates, and created the relative volumes and config-maps and i edited my /etc/hosts

with this setup i am able to do `docker push  kube-registry.com:31000/hello-world`

the last step is to remove that port, and i started playing around with ingress and the solution with ssl passthrough seemed the right way to go so i did this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-registry-ingress
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: kube-registry.com
    http:
      paths:
      - backend:
          serviceName: kube-registry
          servicePort: 5000
  tls:
  - hosts:
    - kube-registry.com
```

from my understanding ssl passthrough should not decrypt traffic on the ingress and just pass along the traffic to the service and back but `docker push  kube-registry.com/hello-world` gives me this error:

> Error response from daemon: Get https://kube-registry.com/v2/: x509: certificate is valid for ingress.local, not kube-registry.com

this is curl output with port (not going through ingress):
```
* Rebuilt URL to: https://kube-registry.com:31000/
*   Trying 192.168.99.100...
* TCP_NODELAY set
* Connected to kube-registry.com (192.168.99.100) port 31000 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=GB; ST=Test State or Province; L=Test Locality; O=Local Secure Registry for Kubernetes; CN=kube-registry.com; emailAddress=test@email.address
*  start date: Dec 28 23:19:10 2017 GMT
*  expire date: Sep 19 23:19:10 2018 GMT
*  issuer: C=GB; ST=Test State or Province; L=Test Locality; O=Local Secure Registry for Kubernetes; CN=kube-registry.com; emailAddress=test@email.address
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET / HTTP/1.1
> Host: kube-registry.com:31000
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Date: Fri, 29 Dec 2017 00:31:18 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Curl_http_done: called premature == 0
* Connection #0 to host kube-registry.com left intact
```

and without port (using ingress):
```
* Rebuilt URL to: https://kube-registry.com/
*   Trying 192.168.99.100...
* TCP_NODELAY set
* Connected to kube-registry.com (192.168.99.100) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  start date: Dec 28 22:51:53 2017 GMT
*  expire date: Dec 28 22:51:53 2018 GMT
*  issuer: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET / HTTP/1.1
> Host: kube-registry.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.13.5
< Date: Fri, 29 Dec 2017 00:32:22 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Cache-Control: no-cache
< Strict-Transport-Security: max-age=15724800; includeSubDomains;
< 
* Curl_http_done: called premature == 0
* Connection #0 to host kube-registry.com left intact
```

i don't understand why in the second case i get ingress's own certificate instead of the one from the registry. am i doing something wrong? 

i also have a [repository](https://github.com/deathcoder/registry-tooling) that sets up everything by using the script reg-tool.sh

ps: i know there is an addon that provides an unsecured registry and that for minikube it might not make much sense what i'm trying to do, i'm just using this little project to understand different components of kubernetes.
