### ISSUE TITLE
[keepalived vip ]  clusterrole RBAC does not verify with v1.9.0

### ISSUE THREAD

**Issue by ArcticSnowman** [kubernetes/contrib#2879]
With the latest K8S V1.9, the list of resources needs to be quoted

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-keepalived-vip
rules:
- apiGroups: [""]
  resources:
    - "pods"
    - "nodes"
    - "endpoints"
    - "services"
    - "configmaps"
  verbs: ["get", "list", "watch"]
```
 or you'll get a validation error..

```
error: error validating "vip-clusterrole.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
```
