### ISSUE TITLE
[election] - Response content is JSON but `Content-Type` header is `text/plain`

### ISSUE THREAD

**Issue by nbrinks** [kubernetes/contrib#2915]
Using the leader election sidecar.
```yaml
# Relevant content
      - image: k8s.gcr.io/leader-elector:0.5
        imagePullPolicy: IfNotPresent
        name: elector
        args:
          - --election=my-election
          - --http=localhost:4040
        ports:
        - containerPort: 4040
          protocol: TCP
        resources:
          requests:
            cpu: 100m
```
Here is an example response from the sidecar.
```
some-user@some-pod-569f9cf4c5-pjh4b:/$ curl -v localhost:4040/
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 4040 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4040 (#0)
> GET / HTTP/1.1
> Host: localhost:4040
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 05 Jun 2018 16:55:12 GMT
< Content-Length: 44
< Content-Type: text/plain; charset=utf-8
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{"name":"some-pod-569f9cf4c5-pjh4b"}
```
I am pretty sure the fix is to place
```go
res.Header().Set("Content-Type", "application/json")
```
before [this line](https://github.com/kubernetes/contrib/blob/master/election/example/main.go#L79) but I am having trouble setting up a development environment to test this.
