### ISSUE TITLE
use annotations to redefine health check endpoints

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#325]
Currently all backends need to serve a 200 on /
https://github.com/kubernetes/contrib/tree/master/Ingress/controllers/gce#health-checks

This makes it hard to run stock apps like word press that don't serve a 200 on /. We should have this configurable, it doesn't need to be blocked on the api exposing health checks.

**Comment by jeremywadsack** [comment]
Updated link to relevant documentation: https://github.com/kubernetes/ingress/tree/master/controllers/gce#health-checks

Also, at this time there appear to be two documented options:
1. Respond with a 200 on '/'. The content does not matter. 
2. Expose an arbitrary url as a readiness probe on the pods backing the Service (see doc for limitations).

**Comment by wadadli** [comment]
/reopen

I think the following scenario.

A `deployment` with two `Service` resources, `service a` and `service b`which both select the same pod that does not respond `200` on `GET` at `/` so the user configures a readiness probe using a path that he knows will return `200` for one of the services, i.e 

```
          ports:
            - name: webadmin // Service A
              containerPort: 8443
              protocol: TCP
            - name: transformer // Service B
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: webadmin
            initialDelaySeconds: 30
            failureThreshold: 30
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: webadmin
            initialDelaySeconds: 30
            failureThreshold: 30
```
If we are to add these services to an ingress resource, `ingress-gce` will use the `readinessProbe` from the `deployment` to configure the health checks for both `service` resources.  The issue is that we have no control of specifying what the `path` should be for health checks on this service in the manifest.

I believe an annotation on the `service` resource would help here, assuming separate service resources are created.
