### ISSUE TITLE
Ansible: CoreOS Support breaks RHEL Support

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/contrib#599]
By introducing support for CoreOS, I can no longer run playbook on RHEL. 

```vim
05:37:33 TASK: [common | Set the bin directory path for CoreOS] ************************ 
05:37:33 fatal: [10.8.55.250] => error while evaluating conditional: ansible_lsb.id == "CoreOS"
```

When running

```
ansible --inventory-file=INVENTORY_FILE masters -m setup
```

ansible_lsb is not defined.

What about to use ``ansible_distribution`` instead of ``ansible_lsb``?

[1] https://github.com/kubernetes/contrib/pull/548

**Comment by ingvagabund** [comment]
@danehans @eparis

**Comment by ingvagabund** [comment]
```
fatal: [10.8.55.250] => error while evaluating conditional: flannel_source_type == "github-release"
```

``flannel_source_type`` facts is not set on non-CoreOS os

**Comment by atosatto** [comment]
I'm replacing `ansible_lsb`with `ansible_distribution` in my local working directory.
I've tested it with the ansible setup module and seems that `ansible_distribution` is set on CoreOS machines.

**Comment by atosatto** [comment]
@ingvagabund I thing that in the case of the `flannel_source_type` we can simply check if the fact is defined if the following way.

```
- name: Install from github
  include: github-release.yml
  when: flannel_source_type is defined and flannel_source_type == "github-release"
```

Do you think it could work?

**Comment by ingvagabund** [comment]
@atosatto thanks for confirmation.

For the ``flannel_source_type`` adding the following before "Install from github" will do:

```
- name: Force flannel_source_type to packages implicitely
  set_fact:
    flannel_source_type: "distribution-release"
  when: ansible_distribution != "CoreOS"
```

**Comment by ingvagabund** [comment]
Faster than I am :) In that case there is third option:

```
- name: Install from github
  include: github-release.yml
  when: ansible_distribution == "CoreOS"
```

**Comment by atosatto** [comment]
I go for the third solution! :smile: 
Let's put it in my local repo and see what happen! ;)

**Comment by ingvagabund** [comment]
Agree :D Let me update my CI to see if those two cases are the last.

**Comment by atosatto** [comment]
Great! :)

**Comment by ingvagabund** [comment]
Hit another one under ``ansible/roles/kubernetes-addons/tasks/main.yml``.

```
fatal: [10.8.55.250] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'python_bin' is undefined", 'failed': True}
```

due to

```
- name: Set python_bin fact for CoreOS
  set_fact:
    python_bin: "/opt/bin/python"
  when: ansible_lsb.id == "CoreOS"
```

**Comment by ingvagabund** [comment]
Again, the python_bin is not defined. {{ python_bin }} is used in

* ansible/roles/kubernetes-addons/templates/kube-addons.service.j2
* ansible/roles/kubernetes-addons/templates/kube-addons.upstart.j2

**Comment by ingvagabund** [comment]
```
- name: Set python_bin fact
  set_fact:
    python_bin: "/opt/bin/python"
  when: ansible_distribution == "CoreOS"
  set_fact:
    python_bin: "python"
  when: ansible_distribution != "CoreOS"
```

This seems to fix it.
