### ISSUE TITLE
Ingress controllers should handle edge cases uniformly x-platform

### ISSUE THREAD

**Issue by aledbf** [kubernetes/contrib#775]
#### Ideas:
- [ ] root URL (mapping to a different url in the upstream)
  - [ ] global per controlller `—root-url`
  - [ ] per Ingress rule using an annotation `root-url`. This means the ingress only contains one rule
- [ ] upstreams to external resources (like /google proxy to http://www.google.cl)

```
kind: Ingress
metadata:
  name: external-ingress
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: external:www.google.cl
          servicePort: 80
        path: /google
```
- [X] rules that overlap (firt rule wins, event with warning) [766](https://github.com/kubernetes/contrib/pull/766)

```
$ kubectl get ing
NAME      RULE          BACKEND   ADDRESS
demo      -                       172.17.4.99
          foo.bar.com
          /             echoheaders-x:80
foo-tls   -                       172.17.4.99
          foo.bar.com
          /             echoheaders-x:80
          bar.baz.com
          /             echoheaders-y:80
```
#### NGINX controller e2e tests:
- [ ] no default backend
- [ ] invalid default backend
- [ ] no ingress
- [ ] single ingress:
  - rule
    - [ ] invalid service
    - [ ] invalid port
    - [ ] no endpoints
    - [ ] no host (it should use the _ nginx server)
    - [ ] without path
- [ ] multiple ingress:
  - rule
    - [ ] invalid service
    - [ ] invalid port
    - [ ] no endpoints
    - [ ] with same path (error or just a warning?)
    - [ ] without path
- [ ] TLS rules:
  - [ ] invalid certs
  - [ ] invalid hosts (fails verification)
  - [ ] invalid service
  - [ ] invalid port
  - [ ] no endpoints
  - [ ] no host (it should use the _ nginx server)
- [ ] tcp configmap
  - [ ] invalid service
  - [ ] invalid port
  - [ ] no endpoints
- [ ] custom nginx configmap
  - [ ] change timeouts
  - [ ] invalid fields
