### ISSUE TITLE
[service-loadbalancer] Error Get http://localhost:1936: dial tcp: lookup localhost on 8.8.8.8:53: no such host

### ISSUE THREAD

**Issue by donbeave** [kubernetes/contrib#788]
Kubernetes: 1.2.1
service-loadbalancer: gcr.io/google_containers/servicelb:0.4

I am getting this error every time when trying to add or delete new service:

```
I0417 09:25:33.638085       6 service_loadbalancer.go:615] Error Get http://localhost:1936: dial tcp: lookup localhost on 8.8.8.8:53: no such host
```

rc.yaml:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: service-loadbalancer
  labels:
    app: service-loadbalancer
    version: v1
spec:
  replicas: 1
  selector:
    app: service-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: service-loadbalancer
        version: v1
    spec:
      nodeSelector:
        role: loadbalancer
      containers:
      - image: gcr.io/google_containers/servicelb:0.4
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
        # All http services
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          hostPort: 1936
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
```
