### ISSUE TITLE
[ansible] Refactor Kubernetes Roles Based on Services

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#838]
The current kubernetes ansible roles are organized into masters and nodes. This makes breaking the master/nodes services into individual units of management, deployment, etc.. In the past, I have seen issues with other projects that do not manage services individually. I suggest changing master into individual roles based on master service, such as:
1. kube-apiserver
2. kube-controller-mansger
3. kube-scheduler

The same for the node role:
1. kubelet
2. kube-proxy

and the client role:
1. kubectl

A single master inventory would stay the same.

site manifest (i.e. cluster.yml) would look like:

```
- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# Install etcd
- hosts: etcd
  sudo: yes
  roles:
    - etcd
  tags:
    - etcd

- hosts: all
  sudo: yes
  roles:
    - common
    - docker
  tags:
    - docker

# install flannel
- hosts:
    - masters
    - nodes
  sudo: yes
  roles:
    - { role: flannel, when: networking == 'flannel' }
  tags:
    - network-service-install

# install kube master services
- hosts: masters
  sudo: yes
  roles:
    - kube-apiserver
   - kube-controller-manager
   - kube-scheduler
   - kubectl
   - kubernetes-addons
  tags:
    - masters
    - dns

# install kubernetes on the nodes
- hosts: nodes
  sudo: yes
  roles:
    - kubelet
    - kube-proxy
  tags:
    - nodes
```

**Comment by ingvagabund** [comment]
Not sure if you will be able to separate master service without increasing complexity. As both ``master`` and ``node`` roles depend on ``kubernetes`` role, each invocation of ``apiserver``, ``scheduler`` and other playbooks will call ``kubernetes`` and ``common`` role. At the same time, ``kubernetes`` role is responsible for generating of certificates and tokens.

If would be great to make sure the ``kubernetes`` role gets run only once. Besides, the entire ``master`` role gets run one more time when you run ``kubernetes-addons`` playbook. Assuming all tasks are idempotent, it does not matter. Still, you run some tasks even when there is no need for it.

I can think of the following scenarios:

* remove dependency of ``kubernetes`` roles from ``master``/``node`` and run the ``kubernetes`` right before them. E.g.

```yaml
- hosts: masters
  sudo: yes
  roles:
   - kubernetes
   - kube-apiserver
   - kube-controller-manager
   - kube-scheduler
   - kubectl
   - kubernetes-addons
  tags:
```

This is not good, as when you decide to run "just" ``kubernetes-apiserver``, ``kubernetes`` role does not get called.

* create one playbook for each ``kube``-like role as you suggest. The ``kubernetes`` role gets called 7-8 times (or maybe my understanding of the ``meta`` is wrong and it gets called only once). Sometimes, you need the ``kubelet`` installed on the master as well. In a case of containerized kubernetes (which is not currently supported), you need kubelet on the master everytime. Well, in any case, you will need one role for each ``kube*``. So instead of shipping ``4`` roles (``kubernetes``, ``master``, ``node``, ``kubernetes-addons``), we will have ``8``. It is a shame, there is no way to create more entry points for one role (the ``main.yml`` in a role is the only entry point). From the point of reusable, it is complete perfect to have one role for each micro-service. From the point of maintainability, it is a lot of code/task execution duplication. 

* break the playbook into smaller independent playbooks. Instead of running one huge playbook at once, call one smaller playbook inside a script. To deploy the cluster, run a sequence of scripts, each script running a playbook. Here, you will get a lot of repetitive tasks again. The benefit of it is that you can keep all master services inside one role. Depending on the tags you set, only the subset of tasks inside a playbook gets called. This way, you keep the master code together. At the same time, it is transparent for a user. On the other hand, you can not include the smaller playbooks inside of a single playbook.

I would love to see ``kube-scheduler``, ``kube-proxy`` and other roles. However, the roles are so tied together it is impossible to do that without loosing benefits of task/code sharing.
