### ISSUE TITLE
Nginx Ingress Controller - the /foo redirection is not working ?

### ISSUE THREAD

**Issue by theobolo** [kubernetes/contrib#860]
Hi guys,

I work with the Ingress / Nginx Ingress Controller, but i can't get the /foo redirection working.

I deployed on a Kubernetes cluster a daemonset of Nginx ingress controller, default backend is the http-default-backend example.

This is my ingress object : 

```
# apimobile Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apimobile-map
spec:
  rules:
  - host: azure.coursierprive.com
    http:
      paths:
      - path: /apimobile
        backend:
          serviceName: application-apimobile
          servicePort: 80
  - host: kube-20160428-120550-loadbalancer.northeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: application-apimobile
          servicePort: 80

```

My second rule is working but not the first one, if i try to reach my api on : azure.coursierprive.com/apimobile 

I face the : backend - 404 

I tried with Jenkins portal instead of my API but i face the same problem.

**Comment by aledbf** [comment]
@theobolo  can you post a gist with the log of the pod?

**Comment by theobolo** [comment]
There it is : https://gist.github.com/theobolo/48724a1ebeef6296d7bfcc2b4feb9844

It's just the log of one Pod of the DaemonSet where we see the request to /apimobile returns 404

**Comment by aledbf** [comment]
@theobolo please execute `kubectl exec nginx-ingress-lb-zg9g9 cat /etc/nginx/nginx.conf`

**Comment by theobolo** [comment]
Added to the Gist

**Comment by aledbf** [comment]
@theobolo please check with the latest version `gcr.io/google_containers/nginx-ingress-controller:0.61`

**Comment by theobolo** [comment]
@aledbf I checked out the last version but i face the same problem,

I tried with many differents frontend but my /foo or /bar redirection always returns a 404 error  :/

Tried with Jenkins, my API, Dashboard ...

In the Nginx Conf i can see the Location rule /apimobile and /jenkins for exemple but it's not working :/

Théo

**Comment by aledbf** [comment]
@theobolo can you post the new nginx.conf?

**Comment by theobolo** [comment]
Yep i updated the Nginx.conf on the Gist.

There is Jenkins on azureapi.coursierprive.com and on azureapi.coursierprive.com/jenkins but not working on /jenkins.

**Comment by aledbf** [comment]
@theobolo please try the image `aledbf/nginx-third-party:0.20` it contains #898 that reverse the order of the locations in nginx so `/` is the last attempted route.

**Comment by theobolo** [comment]
oh ! thx i give you my feedback in few minutes !

**Comment by theobolo** [comment]
So i tried your image but even if the Location  /  is putted after the /jenkins in the nginx.conf it's not working :/

I talked with a collegue and he thinks that's maybe a problem about the URL asked by Nginx to the Jenkins pod. Maybe the Nginx controller is asking jenkins on http://default-jenkins-80/jenkins ? or somehting similar ?

**Comment by theobolo** [comment]
Found something about that : 

http://serverfault.com/questions/444532/reverse-proxy-remove-subdirectory

Maybe is only missing a / at the proxy-pass line in the nginx.conf : 

            proxy_pass http://default-application-apimobile-80;
**            proxy_pass http://default-application-apimobile-80/;**

**Comment by aledbf** [comment]
> `http://default-jenkins-80`

good point, `Location /` this will not redirect to `/jenkins` automatically. Currently is not possible to express this using Ingress rules. Please check https://github.com/kubernetes/contrib/issues/679

> proxy_pass http://default-application-apimobile-80/;

same here. When is requires the final slash or not? This is one of the missing things in Ingress.
https://github.com/kubernetes/kubernetes/issues/16891

If you have an application (not prepackaged app) you can handle this internally (the redirect) as a workaround.

Any idea or feedback is welcomed.

**Comment by theobolo** [comment]
Thanks for all that stuff, i looked all the issues and for the moment it's a very active problem ;)

I think that i'll use the application way as Grafana and the ROOT_URL variable in the YML.
Still looking at this, i'll give you my feedback if i find anything.

I think that the best way is to implement something with Ingress as the Redirect and Rewrite stuff without soliciting the backend app. But the cloud providers apparently are not allowing that :/

Thank you very much for your help Manuel,
I keep in touch

Cheers,
Théo

**Comment by aledbf** [comment]
@theobolo please check the [rewrite](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/rewrite) example
(gcr.io/google_containers/nginx-ingress-controller:0.7)

**Comment by fabiormoura** [comment]
@aledbf I was having the same problem with subroutes. I just tried deploying a pod with nginx-ingress-controller:0.7 and it's working now.

**Comment by theobolo** [comment]
Hey @aledbf it's working well !  I can reach the jenkins Dashboard with the subdirectory /jenkins without changing anything on the controller so it's a good good point !

BTW jenkins is looking for example for some static ressources, even if the path is /jenkins i touch the dahsboard, but the ressources are broken (Css, JS) because it tries to look at /static and not /jenkins/static.

I think that not a problem about the rewrite stuff it's a global problem about the Nginx that not able to rewrite all the paths and just making a symbolic link from /jenkins to / : with the real path=/

If i want to touch jenkins at /jenkins without breaking all the dashboard, i still need to modify the ROOT_URL in the Jenkins controller or in my apps to tell to the CSS that the path as changed to /jenkins. 

So it's very affective for an API or a compute service that not need any attached ressources as a web page.

Tell me if i'm wrong and if i missed something about the concept, i'm really thankful about your update ;)

**Comment by fabiormoura** [comment]
@theobolo I had the same issue with static assets you described on jenkins. 
 Are you using the official docker image?

For the official jenkins image you can set JENKINS_OPTS with --prefix=/jenkins and it won't be necessary to configure a custom rewrite in the ingress specs as @aledbf suggested. Here is one example:

Deployment + Service + Ingress specs
`
kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: jenkins-deployment
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: jenkins
          version: 1.651.2-alpine
      spec:
        containers:
        - name: jenkins
          image: jenkins:1.651.2-alpine
          ports:
          - containerPort: 8080
          env:
          - name: JENKINS_OPTS
            value: "--prefix=/jenkins"
- kind: Service
  apiVersion: v1
  metadata:
    name: jenkins
    labels:
      app: jenkins
  spec:
    ports:
    - port: 80
      targetPort: 8080
    selector:
      app: jenkins
- kind: Ingress
  apiVersion: extensions/v1beta1
  metadata:
#    annotations:
#      ingress.kubernetes.io/rewrite-target: / (suggested by @aledbf but it's not necessary if using JENKINS_OPTS above)
    name: jenkins-ingress
    labels:
      app: jenkins
    namespace: middlewares
  spec:
    backend:
    rules:
      http:
        paths:
        - path: /jenkins
          backend:
            serviceName: jenkins
            servicePort: 80
`

**Comment by theobolo** [comment]
@fabiormoura Thanks for that but i'm already aware of that possibility i called that the ROOT_URL variable in my previous posts witch is the --prefix that we are using for jenkins there.

But by the way that was functional before the rewrite merging, just wondering if the rewrite function could handle that kind of stuff (static ressource rewrite too) without touching or modifying my own apps to add a prefix env variable in the YML or not ;)

But thanks for the solution anyway :)

**Comment by aledbf** [comment]
@theobolo there's an additional annotation `ingress.kubernetes.io/add-base-url:"true"` (I need to add an example) that will "inject" the ingress route in the response body. Sadly this do not work with jenkins because all the links are absolute (if they were relative this works OOTB)

Just as an example in your `/jenkins` rule the body of any page will return 
`<head><base http://$server_name/jenkins/">......`

**Comment by aledbf** [comment]
thanks @fabiormoura for the example

**Comment by theobolo** [comment]
@aledbf thanks for that other annotation it's helpfull in my case :D

**Comment by eghobo** [comment]
@theobolo: did you get any luck with running Grafana under ingress controller? i am having trouble with '/grafana' path, 404 error at login page.

**Comment by theobolo** [comment]
@eghobo I must say that i'm not using Nginx/Ingress controller for the moment, since the Azure cloud provider implementation gives me PublicIP adresses for eachs applications.

Did you change into the Grafana controller the RootPath of the grafana webserver to point to /grafana ?

**Comment by eghobo** [comment]
@theobolo I figure it out (trailing slash was the issue), see examples below (in case if you are interested)

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana-v1
  labels:
    app: grafana
    version: v1
spec:
  replicas: 1
  selector:
    app: grafana
    version: v1
  template:
    metadata:
      labels:
        app: grafana
        version: v1
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:3.1.1
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
              cpu: 100m
              memory: 100Mi
        env:
          - name: "GF_SERVER_ROOT_URL"
            value: "http://example.com/grafana/"
        ports:
        - containerPort: 3000
          name: ui
          protocol: TCP
```
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress-v1
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - example.com
    secretName: nginx-ingress-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /grafana/
        backend:
          serviceName: grafana
          servicePort: 3000
```
