### ISSUE TITLE
Ingress - nginx - option to specify path to nginx.tmpl 

### ISSUE THREAD

**Issue by ajohnstone** [kubernetes/contrib#872]
The nginx.tmpl is stored in the root of the docker image. It would be ideal to place within a directory and/or specify the path to the nginx.tmpl

An example use case is to override the nginx.tmpl using a configmap.

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60      
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.5
        name: nginx-ingress-lb
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10249
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 4444
        args:
        - /nginx-ingress-controller
        - --default-backend-service=default/default-http-backend
        volumeMounts:
          - mountPath: /etc/nginx-template-tmpl
            name: nginx-template-volume
            readOnly: true
      volumes:
        - name: nginx-template-volume
          configMap:
            name: nginx
            items:
            - key: nginx.tmpl
              path: nginx.tmpl

```
Hard coded here.
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx/template.go#L46
