### ISSUE TITLE
ingress - nginx - default http path rule creates an additional server.

### ISSUE THREAD

**Issue by ajohnstone** [kubernetes/contrib#876]
The default http path rule creates an additional server, with an empty server_name and does not map to "_". An Example config.

```
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echomap
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: echoheaders-x
          servicePort: 80
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: echoheaders-x
          servicePort: 80
  - host: bar.baz.com
    http:
      paths:
      - path: /bar
        backend:
          serviceName: echoheaders-y
          servicePort: 80
      - path: /foo
        backend:
          serviceName: echoheaders-x
          servicePort: 80
```
nginx config
```
    server {
        listen 80;
        ...
        server_name ;
    }
    server {
        listen 80;
        ...
        server_name _;
        ...
    }
    server {
        listen 80;
        ...
        server_name bar.baz.com;
        ...
    }
```

full example.

https://gist.github.com/ajohnstone/4b75473fb2e8937d5fc7144d46aad4c4#file-02-nginx-conf-L2-L296
