### ISSUE TITLE
ingress - nginx - specify namespace of service within rules

### ISSUE THREAD

**Issue by ajohnstone** [kubernetes/contrib#878]
It would be ideal to specify another namespace of a service within the ingress rules.

my use case is to wrap authentication over the logging without providing kubernetes accounts to developers/qas etc.

"ELB -> bitly/oauth2_proxy -> ingress routing -> logging".

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: default
  spec:
    rules:
    - http:
        paths:
        - backend:
            nameSpace: kube-system
            serviceName: kibana-logging
            servicePort: 5601
          path: /logs
```

**Comment by aledbf** [comment]
@ajohnstone please check https://github.com/kubernetes/kubernetes/issues/17088

**Comment by thockin** [comment]
Dup of kubernetes/kubernetes#17088

**Comment by chestack** [comment]
my workaround:

1.  serviceA in namespaceA
2. create serviceB in namespaceB 
```
spec:
    ...
    type: ExertalName
    externalName: serviceA.namespaceA.svc.cluster.local
```
3. add ingress rule into ingressB in namespaceB
```
     - path: /****
        backend:
          serviceName: serviceB
          servicePort: ***
```
